.so ../macros
.TH unget File %G% "BitMover, Inc." BitKeeper
.\"    =============== Un-editing files ===============
.SH NAME
bk unget \- destroy any unchecked in changes to specified files
.SH SYNOPSIS
.B bk unedit [
.IB files... ]
.br
.B bk unget [
.IB files... ]
.SH DESCRIPTION
.LP
If you wish to discard any modifications you have made to a file,
you can use the unedit command.  For each listed file, unedit will
discard the write lock and discard the checked out file and ANY CHANGES
YOU HAVE MADE TO THE FILE.  Use this command only when you have made
changes to a file that you want to throw away.  If you want to clean
up only those files without changes, use the bk clean command.
.LP
The unedit command will not autoexpand the file list, you must explicitly
name each file you want to unedit.
.LP
unget is an alias for unedit; unget is the ATT SCCS compatible name.
.SH "SEE ALSO"
.SA clean
.br
.SA unlock
.\" help://File/unget
.\" help://File/unedit
