.so ../macros
.TH difftool GUI-tools %G% "BitMover, Inc." BitKeeper
.SH NAME
bk difftool \- BitKeeper Graphical Diff Tool
.SH SYNOPSIS
.LP
.B bk difftool
.I file1
.br
.B bk difftool
.BI -r 1.3
.I file1
.br
.B bk difftool
.BI -r 1.3 -r 1.9
.I file1
.br
.B bk difftool
.I file1 file2
.SH DESCRIPTION
.LP
The
.B difftool
command is a side-by-side differences viewer that shows each
file in a window, with the differences color coded.
You can move back and forth through the diffs using the keys
described below.
All differences are highlightd, but as you move to a new diff,
that diff becomes highlighted in a bold font.
.SH ARGUMENTS
.LP
If only one file is specified and that file is a locked and modified file,
.B difftool
will diff the most recent revision against the locked version.
.LP
If a revision and a checked out file are specified
.B difftool
diffs that version against the checked out file.
.LP
If two revisions and a file are specified
.B difftool
diffs those two versions of the file.
.LP
If two files are specified,
.B difftool
diffs those two files.
.SH "KEY BINDINGS"
.\".de tp
.\".	sp -.5
.\".	TP
.\"..
.TP .9i
.B Home
Scroll both files to the top
.tp
.B End
Scroll both files to the bottom
.tp
.B PageUp
Scroll both files one screen up
.tp
.B PageDown
Scroll both files one screen down
.tp
.B Up
Scroll both files one line up
.tp
.B Down
Scroll both files one line down
.tp
.B Left
Scroll both files to the left
.tp
.B Right
Scroll both files to the right
.tp
.B q
Quit
.tp
.B space
Next diff
.tp
.B n
Next diff
.tp
.B p
Previous diff
.tp
.B .
Center the current diff on the screen
.SH SEE ALSO
.LP
.B bk help diffs
.br
.B bk help fmtool
