.so ../macros
.TH Introduction GUI-tools %G% "BitMover, Inc." BitKeeper
.\"    ============== BitKeeper Graphical User Interface  ==============
.SH NAME
Introduction
.SH DESCRIPTION
.LP
While it is possible to use BitKeeper as an "ASCII-only" tool, the GUI
tools help make BitKeeper exceedingly powerful and easy to use. In this
section, we provide a brief overview of the GUI tools, although each tool
is covered more thoroughly in its own section.
.TP
.B citool
Run this to see which files need to be checked in. Also, files can
be excluded from the changeset.
.TP
.B csettool
Used to view changesets.  Shows the history and the 
diffs of each file in a changeset.
.TP
.B difftool
Used for side-by-side viewing of differences.
.TP
.B helptool
Graphical interface for online Bitkeeper documentation.
.TP
.B fmtool
Two-way file merge.  Usage: fm left right output.
.TP
.B fm3tool
Three-way file merge.  Usage: fm3 left GCA right output.
.TP
.B renametool
Used to find renames when importing a patch.  Called
automatically from "bk import -tpatch".
.TP
.B sccstool
Browses revision control files listed on the
command line.  Click the left mouse once on a rev
to see that rev's history.  Double click the left
mouse to see that all of the files that make up that
changeset. 
To see the side-by-side diffs between two revs, click
on one rev with the left mouse button and click on the
other rev with the right button and then click on the
"View changesets" button on the upper right corner of 
the window.
.SH "SEE ALSO"
.SA citool
.br
.SA csettool
.br
.SA difftool
.br
.SA helptool
.br
.SA fmtool
.br
.SA fm3tool
.br
.SA renametool
.br
.SA sccstool
.\" help://GUI-tools/GUI
.\" help://GUI-tools/gui
