all: dev

p:
	@./build.sh p

g:
	@./build.sh g

dev:
	@./build.sh dev

install:
	@./build.sh install

uninstall:
	@./build.sh uninstall

distrib:
	@./build.sh distrib

clean:
	@./build.sh clean

distclean:
	@./build.sh distclean
