.so ../macros
.TH qs_bkd General %G% "BitMover, Inc." BitKeeper
.\"    =================== Quickstart Admin =========================
.SH NAME
Quickstart Admin
.SH DESCRIPTION
.LP
Here are examples how to configure the bk daemon for both read-only and
read-write modes.  We show how to export all repositories on a system
in both read-write and read-only mode and we show how to export only
a specific repository in read-write and read-only mode.
.AX
# Configure BitKeeper daemon for read-only 
# access for all repositories
bk bkd -d -xpush

# Configure BitKeeper daemon for read-write 
# access for all repositories
bk bkd -d

# Access a specific repository when multiple 
# ones are being exported
bk clone bk://host.domain/some/dir/master ~/my_tree

# Configure a specific BitKeeper repository 
# for read-write access
cd /master/repository
bk bkd -d -p6666 -xcd

# Configure a specific BitKeeper repository 
# for read-only access
cd /master/repository
bk bkd -d -p4444 -xcd -xpush

# Access a repository bound to a specific port
bk clone bk://host.domain:6666 ~/my_tree
.XA
.SH "SEE ALSO"
.B bk help bkd
.br
.B bk help quickstart
