.so ../macros
.TH quickstart General %G% "BitMover, Inc." BitKeeper
.\"    =================== BitKeeper quickstart ===================
.SH NAME
Quickstart guides
.SH DESCRIPTION
.LP
Quickstart guides are recipes for accomplishing common tasks with
BitKeeper.  The guides contain little or no explanations.  Each command
has detailed help which you can see by running bk help <command>.
.LP
Project leads should read the bk help qs_setup 
and bk help qs_bkd sections.  Developers
who just want to use an existing package only 
need to read bk help qs_developer.
.SH "SEE ALSO"
.B bk help qs_bkd
.br
.B bk help qs_developer
.br
.B bk help qs_setup
.SH ALIASES
.BR Quickstart (General)
