.so ../macros
.TH quickstart General %G% "BitMover, Inc." BitKeeper
.\"    =================== BitKeeper quickstart ===================
.SH NAME
Quickstart guides
.SH DESCRIPTION
.LP
Quickstart guides are recipes for accomplishing common tasks with
BitKeeper.  The guides contain little or no explanations.  Each command
has detailed help which you can see by running
.if t \{\
.B bk
.BI help \ command .
\}
.if n
bk help <command>
.LP
Project leads should read the
.B bk help qs_setup 
and
.B bk help qs_bkd
sections.  Developers
who just want to use an existing package only 
need to read
.B bk help
.BR qs_developer .
.SH "SEE ALSO"
.B bk help qs_bkd
.br
.B bk help qs_developer
.br
.B bk help qs_setup
.\" help://General/Quickstart
