#!/bin/sh

# Copright (c) 1999 Larry McVoy
# %K%

if [ X"$*" != X ]
then	list="$*"
else	list=`echo t.*`
fi

for i in $list
do	n=${i#t.}
	echo ------------ $n tests
	cat setup $i cleanup | sh
	EXIT=$?
	if [ $EXIT != 0 ]
	then	echo Test exited with error $EXIT
		exit $EXIT
	fi
done
echo ------------------------------------------------
echo All requested tests passed, must be my lucky day
echo ------------------------------------------------
exit 0
