.so ../macros
.TH abort Repository %G% "BitMover, Inc." BitKeeper
.\"    ============ Aborting a failed pull/push/resync  ============
.SH NAME
bk abort \- abort a failed pull, push, or resync
.SH SYNOPSIS
.B bk abort [\-f] [
.I repository root
.B ]
.SH DESCRIPTION
.LP
The abort command can be used to clean up a failed update of a repository
so that you can try the update again.  Updates sometimes fail, leaving
the PENDING and RESYNC directories behind.  Since the existence of the
RESYNC directory acts as a global repository lock, you probably don't
want to leave it there for an extended period of time.
.LP
If the update (i.e., a bk pull/push/resync) failed and there has been no
manual resolve work done yet, there is no harm in aborting and trying
again.  If manual resolution has been done, it may be worth the effort
to figure out what went wrong and try and fix it.
.SH OPTIONS
.TP
.B -f
Do not prompt for confirmation, just do it.
.SH BUGS
.LP
Abort could go look to see if you have done any work and refuse to
abort without
.B \-f
if you have.
.SH "SEE ALSO"
.B bk help pull
.br
.B bk help push
.br
.B bk help resync

