.so ../macros
.TH backups Repository %G% "BitMover, Inc." BitKeeper
.\"    =============== Safeguarding your BitKeeper repositories ===============
.SH NAME
backups
.SH DESCRIPTION
.LP
BitKeeper repositories with no pending files can be safely backed up
with any backup tool, such as tar or dump, etc.
.LP
.SH WARNING
.LP
If the repository has pending files (files which are checked in but not
yet committed to a changeset), then saving and restoring the repository
should be done carefully.  Problems can arise if the repository is
restored multiple times and the same pending deltas are committed 
to different changesets.  In other words, the following will cause
problems:
.AX
cd REPO
bk edit foo.c
echo "I am a pending delta not yet committed" >> foo.c
bk delta -yPENDING foo.c
cd ..
cp -r REPO COPY
cd REPO
bk commit
cd ../COPY
bk commit
.XA
.LP
Why is it a problem?  Because the two commits both created a changeset,
and the changesets are different.  This means that the same delta to
foo.c now belongs to two different changesets.  It is not fatal when
this happens, but it may make it difficult to roll backwards to this
point.
.SH SUGGESTION
.LP
If what you want is a copy of the repository, use bk clone to copy
it, not tar, cp, or some other file by file copy.
.SH "SEE ALSO"
.SA pending
.br
.SA status
.\" help://Repository/copying
.\" help://Repository/copy
