.so ../macros
.TH changes Repository %G% "BitMover, Inc." BitKeeper
.\"    ====================== changesets ======================
.SH NAME
bk changes \- show what changesets have been checked 
into your local work area.
.SH SYNOPSIS
.B bk changes [\-v
.IB num ] 
.B [\-r
.IB revs ]
.SH OPTIONS
.TP
.AN \-r rev
Specifies the changesets to be listed, i.e., 1.100..
.TP
.B \-t
Only list changesets which are tagged.
.TP
.B \-v
Shows individual file logs as well as changeset logs.
.TP
.AN \-v num
As above, but indent per file 
.I num 
spaces.
.SH EXAMPLES
Sample output:
.AX
ChangeSet@1.607, 2000-02-21 14:05:25-08:00, awc@host.com
  update citool to use the "bk unedit" interface. 

ChangeSet@1.606, 2000-02-21 13:35:21-08:00, awc@host.com
  This fix allow BitKeeper to be installed in non-standard directory.
  The install directory is computed from the $PATH variable and 
  the bk symlink.

ChangeSet@1.605, 2000-02-20 01:32:19-08:00, lm@host.com
  Fix a diagnostic in pull.
  An aborted attempt at key compression.
.XA
.SH "SEE ALSO"
.B bk help commit
.br
.B bk help pending
.br
.B bk help sccstool
