.so ../macros
.TH diffs Basics %G% "BitMover, Inc." BitKeeper
.SH NAME
bk diffs \- shows differences in modified files
.SH SYNOPSIS
.B bk diffs
.BI [ options
.B ]
.BI [ files
.B ]
.SH DESCRIPTION
.LP
To view changes you have made to all of the files in a directory
since checking the files out, type:
.AX
$ bk diffs | more
.XA
To see the changes for all files in your tree, go to the top level
of your repository and do the following:
.AX
$ bk -r diffs | more
.XA
The 
.B bk diffs
command supports context, unified, procedural, and side-by-side diffs.
.LP
You can also diff specific revisions. For example:
.AX
$ bk diffs -r1.2..1.4 foo.c
$ bk diffs -dAlpha..Beta foo.c
.XA
.SH OPTIONS
.TP
.B -a
do diffs for all sfiles
.TP
.B -c
do context diffs
.TP
.B -D
prefix lines with dates
.TP
.AN -d dates
diff using date or symbol
.TP
.B -f
prefix lines with file names
.TP
.B -h
don't print headers
.TP
.B -M
prefix lines with revision numbers
.TP
.B -n
do RCS style diffs
.TP
.B -P
produce patch diffs, similar to
.B diff -Nur
.TP
.B -p
procedural diffs, like
.B diff -p
.TP
.AN -r r
diff revision 
.IR  r .
.TP
.B -s
display side-by-side
.TP
.B -U
prefix lines with user names
.TP
.B -u
do unified diffs
.TP
.B -v
be verbose about non-matching ranges
.SH SEE ALSO
.LP
.SA difftool
.br
.SA export
.\" help://Basics/differences
.\" help://Basics/sdiffs
