.so ../macros
.TH sccslog Basics %G% "BitMover, Inc." BitKeeper
.SH NAME 
bk sccslog \- like prs, except it sorts deltas by date across all files
.SH SYNOPSIS
.B sccslog [-Cpv]
.OA c d
.OA r r
.BI [ file list... ] |
.BI [ - ] |
.B [ ]
.SH DESCRIPTION
.LP
.B sccslog
displays part or all  of  the  SCCS  file in a user supplied format.
.SH OPTIONS
.TP
.AN -c dates
Cut off dates.  See
.IR range (1)
for details.
.TP
.B -C
Produce comments for a changeset.
.TP
.B -p
Show basenames instead of full pathnames.
.TP
.AN -r r
Specify a revision or a part of a range.
.TP
.B -v
Be verbose about errors and processing.
.LP
Note that
.I date
may be a symbol, which implies the date of the delta which matches the symbol.
.LP
Range specifications:
.TP
.I -r+
prints the most recent delta
.TP
.I -r1.3..1.6
prints all deltas 1.3 through 1.6
.TP
.I -d9207..92	
prints all deltas from July 1 '92 to Dec 31 '92
.TP
.I -d92..92	
prints all deltas from Jan 1 '92 to Dec 31 '92
