A list of bkd commands sketched out
===================================

This file tries to document the resync daemon commands.

clone - clone the current repository
    USAGE: clone
    You must have used "root" to set a root repository.

    This command just runs bk -r sfio -o which will produce an sfio
    file of the entire repository on stdout.  It's up to the calling
    client to take that and apply it.

    EXIT: exits on command completion

list - list all repositories on this system
    USAGE: list
    If there are repositories which have been advertised with the "advertise"
    command, then they are listed.

    EXIT: does not exit on command completion

pull - pull remote changes from current repository into client repository
    USAGE: pull [-n]
    You must have used "root" to set a root repository.

    This command expects a set of keys in stdin, as generated by:
	bk -R prs -bhad:KEY: ChangeSet
    followed by a single line containing:
	@END@
    with no leading/trailing white space.

    The command will produce some status on stderr about what is being sent,
    and then send a patch on stdout.

    EXIT: exits on command completion

push - push and apply local changes into remote repository
    USAGE: push [-n]
    You must have used "root" to set a root repository.

    This command will send a set of keys on stdout, as generated by:
	bk -R prs -bhad:KEY: ChangeSet
    followed by a single line containing:
	@END@
    with no leading/trailing white space.

    The client is responsible for comparing those keys to local keys and if
    the local keys are a strict superset, then sending a patch.

    EXIT: exits on command completion

quit - disconnect and end conversation
root - set the repository to path or key; keys mean masters only
status - Show status for repository
verbose - create a back channel for status/diagnostics (stderr)
