#!/bin/bash
# Copyright 2015-2016 BitMover, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Post-install script for BitKeeper's OS X package installer.
# This script must be named "postinstall". It calls an L
# script "postinstall.l" to do all the work.

BK="$DSTROOT/BitKeeper.app/Contents/Resources/bitkeeper/bk"
BK_GUI="yes" "$BK" wish postinstall.l >OUT 2>&1 || {
	mv OUT /tmp/bk-install-failure.txt
	exit 1
}
exit 0
