#!/bin/bash
#
# Post-install script for BitKeeper's OS X package installer.
# This script must be named "postinstall". It calls an L
# script "postinstall.l" to do all the work.

BK="$DSTROOT/BitKeeper.app/Contents/Resources/bitkeeper/bk"
BK_GUI="yes" "$BK" wish postinstall.l >OUT 2>&1 || {
	mv OUT /tmp/bk-install-failure.txt
	exit 1
}
exit 0
