.so bk-macros
.TH "bk admin" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk admin \- administer \*(BK files (tags, checksums, validation)
.SH SYNOPSIS
.B bk admin 
.I
options
.BKARGS
.SH DESCRIPTION
.LP
The 
.B admin
command is used to create and/or administer \*(BK files.
.SH OPTIONS
.\" Undocumented on purpose:
.\" ATT compat: -a, -e, -d, -n
.\" -s
.if t .TP .8i
.if n .TP 1.5i
.B \-0
add a 1.0 delta if there is not one already
.nr tp_space .065i
.tp
.B \-B
make the landing pad bigger
.tp
.B \-C
remove the changeset marks (very rarely used, \fBnot\fP recommended)
.tp
.B \-CC
remove the changeset marks and pointer (very rarely used, \fBnot\fP recommended)
.tp
.OPTreq \-E enc
force file to be encoded with 
.ARG enc ,
which may be:
.if t .RS .8i
.if n .RS .4i
.if t .tp 1.1i
.if n .tp 1.1i
.BR text
regular text file (typical)
.tp
.B ascii
same as 
.ARG text
.tp
.B binary
force binary file (data will be uuencoded in s.file)
.tp
.RE
.tp
.OPTreq \-f flag
set 
.ARG flag 
which can be any of:
.if t .RS .8i
.if n .RS .4i
.if t .tp 1.1i  
.if n .tp 1.1i
.B ALWAYS_EDIT
always follow a delta with an edit, leaving a locked file.
.tp
.B BITKEEPER
mark the file as a \*(BK file (very rarely used, \fBnot\fP recommended)
.tp
.B EXPAND1
expand keywords in first keyword containing line only (printf conflicts)
.tp
.B RCS
expand RCS keywords, i.e., $\fIkeyword\fP$ etc.
.tp
.B SCCS
expand SCCS keywords, i.e., %\fIK\fP% etc.
.tp
.B YEAR4
display dates as 4 digit years (breaks \*(AT compatibility)
.sp .25
.ti -1.1i
Flags with arguments are:
.tp
.OPTreq DEFAULT= rev
set the default branch or revision used by the
.BR bk\ get
command.
.RE
.tp
.OPTreq \-d f
delete flag
.ARG f ,
reverting to default behaviour.
.tp
.OPTreq \-F f
delete flag 
.ARG f ,
reverting to default behaviour.
.tp
.B \-h
check s.file structure in general, but limited to \*(AT features.
.tp
.B \-hh
as above, but also check \*(BK structure
.tp
.B \-hhh
as above, but also check time stamps
.tp
.B \-H
same as -h, plus check that file contents are ASCII
.tp
.OPTopt \-i file
read initial text from
.ARG file
(default stdin)
.tp
.OPTreq \-m mode
set the mode of the file;
.ARG mode
is in the form 
.BR -rwxrwxrwx .
.tp
.OPTreq \-M merge
Mark branch specified by revision
.ARG merge
as merged into 
.ARG rev ,
if specified, or top of trunk.
.tp
.OPTopt \-p path
set path of the most recent delta to 
.ARG path ,
if
.ARG path
was specified, otherwise use the current file location.  Note: not a timesafe
operation, typically used only by 
.BR bk\ import .
.tp
.B \-q
run quietly
.tp
.OPTreq \-r rev
may be used with 
.B \-M
to specify a revision other than top of trunk,
and, when not in a \*(BK repository, with 
.B \-i
to specify the initial revision.
.tp
.OPTequal -S sym rev
associate symbolic name (tag)
.ARG sym
with revision
.ARG rev
.tp
.OPTreq \-t file
read description text from 
.ARG file
and replace the current descriptive text, if any
.tp
.B \-T
clear description text
.tp
.B \-u
force all timestamps to be increasing (very dangerous, this changes the keys)
.tp
.OPTreq \-y comment
make 
.ARG comment
be the checkin comment for the initial checkin (only valid with 
.B \-i
and
.BR \-n ).
.tp
.B \-z
recalculate file checksum
.tp
.OPTreq \-Z alg
compress stored s.file with 
.ARG alg
which may be:
.if t .RS .8i
.if n .RS .4i
.if t .tp
.if n .tp 1.1i
.B  gzip
like 
.BR gzip (1)
.tp
.B none
no compression
.RE
.SH BUGS
.LP
This command does way too much and is likely to be split apart.
Do not depend on these options for scripts.
.SH SEE ALSO
.LP
.SA chmod 1
.SA delta 1
.SA get 1
.SA prs 1
.SA tag 1
.SA keywords
.SH CATEGORY
.B Admin
