.so bk-macros
.TH "bk annotate" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk annotate \- provide annotated listing of source files
.SH SYNOPSIS
.Bc bk annotate [\-adkmNnu] [
.OPTreq \-c dt
.Bc ] [
.OPTreq \-r rev
.B ]
.BKARGS
.br
.Bc bk sccscat [\-dmnNu] [
.OPTreq \-c dates
.Bc ] [
.OPTreq \-r rev
.B ]
.BKARGS
.SH DESCRIPTION
.LP
Annotated listings are useful for deeper understanding of your source
base, i.e., when you are tracking down bugs.  The annotations add an
extra level of information which can be useful.
.LP
\*(BK has two kinds of annotations:  annotations of a specific version,
and annotations of all (or some) versions (the second form is unique to \*(BK).
.SH ANNOTATE
.LP
The 
.B annotate
command will display a specific version of a file with annotations. 
The default annotations are the revision in which the change was
made and the user who made that change.  Specifying any options
overrides all of the default options.
.SH SCCSCAT
.LP
By default,
.B bk sccscat
will display 
.B all
lines in 
.B all
versions of a file, with each version of a line grouped closely with
other versions of that line.  This is useful for determining when a
particular feature was added.
.LP
.B bk sccscat 
can restrict the set of lines displayed to those lines added in a 
specified revision or date range.  In that case, the whole file is
not displayed, instead, only the lines which were added in that 
range of changes are displayed.  This form is usually a result of
specifying a range to
.BR "bk grep" .
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-a
Align prefix output in a human readable form.  Used with one of
the following options
.BI [ mNnud ].
.tp
.OPTreq \-c date
.B bk annotate: 
annotate the latest version before
.ARG date .
See bk range for date specs;
.br
.B bk sccscat:
annotate the set of versions matching the range
.ARG date .
See bk range for date specs.
.tp
.B \-d
Prefix each line with the date of last modification.
.tp
.B \-k
.B bk annotate:
do not expand RCS or SCCS keywords.
.B bk sccscat
never expands keywords.
.tp
.B \-m
Prefix each line with the revision of last modification.
.tp
.B \-N
Prefix each line with its line number.
.tp
.B \-n
Prefix each line with the filename.
.tp
.OPTreq \-r rev
.B bk annotate: 
annotate this revision;
.br
.B bk sccscat:
annotate the lines added by this revision.
.tp
.B \-u
Prefix each line with the user who last modified it.
.SH SEE ALSO
.LP
.SA get 1
.SA grep 1
.SA range 1
.SA revtool 1
.\" help://sccscat
.\" help://bk-sccscat
.\" help://sccscat.1
.\" help://bk-sccscat.1
.SH CATEGORY
.B File
