.so bk-macros
.TH "bk base64 1 2002/09/03 "\*(BC" "\*(UM"
.SH NAME
bk base64 \- RFC 1341 base64 encoding and decoding
.SH SYNOPSIS
.B bk base64 [\-d]
.SH DESCRIPTION
.LP
The
.B base64
command is a filter that encodes arbritrary data from stdin to a ASCII
format that only uses the characters A-Z,a-z,0-9,/,+,= and newline to
encode the data.  This data can easily be emailed without being mangled.
If the 
.B \-d
option is passed then the encoding is unpacked to the orignal
data.
.SH OPTIONS
.if t .TP .6i
.if n .TP 1i
.B \-d
Decode base64 data to the orignal byte stream.
.SH "SEE ALSO"
.SA crypto 1
.SH CATEGORY
.B Utility
