.so ../bk-macros
.TH "bk bin" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk bin \- show binary installation directory
.SH SYNOPSIS
.\"
.B bk bin
.SH DESCRIPTION
.LP
Returns the full path to the directory containing the bk installation.
.LP
To read man page documentation in a single file do:
.DS
vi `bk bin`/bkhelp.txt
.DE
.SH CATEGORY
.B Utility
