.so bk-macros
.TH "bk" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk bk \- \*(BK source management system front end
.SH SYNOPSIS
.B bk 
.ARG command 
.Bc [
.ARGc options
.B ]
.br
.B bk \-R
.ARG command 
.Bc [
.ARGc options
.B ]
.br
.Bc bk [
.OPTopt \-r dir
.B ]
.ARG command
.Bc [
.ARG options
.B ]
.br
.Bc bk [\-sfiles_opts] [
.OPTopt \-r dir
.B ]
.SH DESCRIPTION
.B bk
is the front end to all \*(BK commands.
All \*(BK commands are prefixed with 
.B bk
in order to avoid ambiguity with
non-\*(BK commands that might be on the system such as 
.B get
and
.BR ci .
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-R
Change directories to the root of the repository before running the command.
.tp
.OPTopt \-r dir
Starting at 
.ARG dir ,
or the repository root if 
.ARG dir
was not specified, generate a list of sfiles and pass them to the command.  
The command is run in
.ARG dir
or the root of the repository if no directory was specified.
.tp
.B \-sfiles_opts
Used as a shortcut for sfiles; any sfiles options may be passed.  For example,
the following commands are equivalent:
.br
bk -cr 
.br
bk -r sfiles -c
.br
.SH NOTE
.LP
The following commands are equivalent:
.if n .sp -1
.DS
bk -r get
bk -R sfiles | bk -R get -
cd `bk root`; bk sfiles | bk get -
.DE
.SH "SEE ALSO"
.SA sfiles 1
.SH CATEGORY
.B Repository
