.so ../bk-macros
.TH "bk bin" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk bin \- show binary installation directory
.SH SYNOPSIS
.\"
.B bk bin
.SH DESCRIPTION
.LP
Returns the full path to the directory containing the
\*[BK] installation.
.LP
To read all command documentation in a single file do:
.DS
vi \`bk bin\`/bkhelp.txt
.DE
.SH CATEGORY
.B Utility
