.so ../bk-macros
.TH "bk base64" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk base64 \- RFC 1341 base64 encoding and decoding
.SH SYNOPSIS
.B bk base64
.[B] \-d
.SH DESCRIPTION
.LP
The
.B bk base64
command is a filter that encodes arbitrary data from stdin to a ASCII
format that only uses the characters
.CR A-Z ,
.CR a-z ,
.CR 0-9 ,
.CR / ,
.CR + ,
.C =
and newline to encode the data.
This data can easily be emailed without being mangled.
If the 
.B \-d
option is passed then the encoding is unpacked to the original
data.
.SH OPTIONS
.TP
.B \-d
Decode base64 data to the original byte stream.
.SH "SEE ALSO"
.SA crypto
.SA unwrap
.SA wrap
.SH CATEGORY
.B Utility
