.so ../bk-macros
.TH "bk csets" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk csets \- run changes or csettool on last set of incoming changes
.SH SYNOPSIS
.B bk csets
.[B] \-t
.SH DESCRIPTION
.LP
The
.B csets
command will run the
.B bk csettool
command on the last set of 
changesets imported into this repository with a
.BR bk\ pull ,
or
.BR bk\ push .
This is useful for tracking down problems and/or doing a quick review.
.SH OPTIONS
.tp
.B \-t
Use 
.B bk changes
to display the changesets (text mode).
.SH BUGS
The -t option should be implied if there is no graphical display to be found.
.SH "SEE ALSO"
.SA changes
.SA csettool
.SA pull
.SA push
.SH CATEGORY
.B Repository
