.so ../macros
.TH "bk csets" 1 08/18/00 "*(BC" *(BK
.\"    =============== Viewing recent changesets ===============
.SH NAME
bk csets \- run csettool on last set of imported changes
.SH SYNOPSIS
.B bk csets
.SH DESCRIPTION
.LP
The csets command will run the csettool command on the last set of 
changesets imported into this repository with a pull, push, or resync.
This is useful for tracking down problems.
.SH "SEE ALSO"
.SA csettool
.SH CATEGORY
.B Repository
