.so bk-macros
.TH "bk chmod" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk chmod \- change the mode of a file and save it
.SH SYNOPSIS
.B bk chmod 
.ARG mode
.ARG file
.BKARGS
.SH DESCRIPTION
.LP
The
.B chmod
command changes the stored file modes for files in the
repository.  File modes are normally whatever the file was when it was
checked in to BitKeeper.  When changes to the mode need to be made,
use 
.B bk chmod
command and not the system's
.B chmod
command.
.LP
The command respects whatever syntax your native
.B chmod
command uses.
It does this by running
.B chmod
on the file and then copies the resulting
modes into the revision history.
.SH SEE ALSO
.LP
.SA admin 1
.BR chmod (1)
.SH CATEGORY
.B File
