.so bk-macros
.TH "bk clone" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper clone ======================
.SH NAME
bk clone \- create a new copy of a package
.SH SYNOPSIS
.Bc bk clone [\-q] [ 
.OPTequal E envvar val
.BC ] [
.OPTreq \-r rev
.Bc ] [
.OPTopt \-z 0\-9
.B ]
.ARG source
.ARG destination
.SH DESCRIPTION
.LP
The clone command copies from the source repository and creates a
copy at the destination.  See 
.B bk help parent
for information on
the syntax of
.ARG source
and
.ARG destination .
.LP
If 
.ARG rev
is specified, the cloned repository will include only
changesets up to and including 
.ARG rev .
.LP
The cloned repository remembers from which repository it was cloned.
The source repository is known as the "parent", while the newly cloned
repository is known as the "child".
.LP
Subsequent updates to the child can be done by running 
.BR bk\ pull .
Changes made in the child can be pushed back into the parent by running
.BR bk\ push .
.LP
Only completed changesets are cloned.  Any pending deltas are removed
from the child before the clone completes.
.SH OPTIONS
.TP \w'\-r<rev>\ 'u
.B \-q
Run quietly.
.tp
.OPTequal \-E env val
Export environment variable to remote site.
.tp
.OPTreq \-r rev
Clone the repository up to and including cset 
.ARG rev .
.tp
.OPTreq \-z d
Do compression at level 
.ARG d ,
if possible; default is \-z6.
Compression is possible when using ssh or the \*(BK daemon,
but not with rsh.
.SH "SEE ALSO"
.SA bkd 1
.SA parent 1
.SA pull 1
.SA push 1
.SA triggers 1
.SH CATEGORY
.B Repository
.br
.B Common
