.\" help://comment
.so bk-macros
.TH "bk comments" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk comments \- change checkin comments
.SH SYNOPSIS
.Bc bk comments [\-p] [
.OPTreq \-C csetrev
.Bc ] [
.OPTreq \-r rev
.Bc ] [
.OPTreq \-y cmt
.Bc ] [
.OPTreq \-Y file
.B ]
[file ...] [\-]
.SH DESCRIPTION
.LP
The
.B comments
command changes the stored comments for a revision controlled file.
The comments may be specified on the command line, or if they are
not, you will be placed in your editor to type in the comments.
.LP
If given
.B \- for a file argument, then 
.B comments
will read a list of files and comments to be edited in batch.
The format is like:
.DS
### Comments for file.c|1.23
this is a sample comment
### Comments for file2.h|1.2.3.4
these are
other comments
.SH OPTIONS
.if t .TP .8i
.if n .TP 1.2i
.OPTreq \-r rev
Change the comments for the specified revision.  The default is the
most recent revision.
.tp
.OPTreq \-y comment
Use
.ARG comment
as the new comment for all files.
.tp
.OPTreq \-Y file
Use the contents of
.ARG file
as the new comment for all files.
.tp
.OPTreq \-C rev
Edit all the file comments on the requested changeset at once.
.tp
.B \-p
Generate the list of all comments in the files requested and write them to
stdout.  This file can be edited and then later fed into 
.B bk comments -
on stdin to change the comments.
.tp
.SH BUGS
.B Nota bene:
if the deltas being commented have been committed to a changeset and
have been pulled out of this repository, the comment changes will not
propagate on the next bk pull.  It is strongly suggested that you use
this only on uncommitted deltas which have not  been pulled or cloned.
In the future, we will add a way of enforcing this.
.SH SEE ALSO
.LP
.SA prs 1
.SA sccslog 1
.SH CATEGORY
.B File
