.so bk-macros
.TH "bk config-etc" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk config-etc \- configuring \*(BK per repository
.SH DESCRIPTION
.LP
Repository preferences can be defined in the BitKeeper/etc/config file.
The general format for the repository preference config file is 
.DS
[filter:]preference:option
.DE
Currently, checkout is the only user preference supported.
To set, add a line to the BitKeeper/etc/config file as follows:
.DS
checkout:option
.DE
Where option is one of:
.RS 1i
.TP
.B get
Automatically do a bk get
.ARG file
after doing a bk delta
.ARG file .
(Checkout in read-only mode.)
.tp
.B edit
Automatically do a bk edit
.ARG file
after doing a bk delta
.ARG file .
(Checkout in edit mode.)
.tp
.B none
Clear the gfile after doing a bk delta
.ARG file .
(This is the default.)
.RE
.LP
Preferences can be set per user, per host, or per repository via filters.
.RS 1i
.TP
.B per user
[jdoe:]checkout:get
.tp
.B per host
[@xyz.com:]checkout:none
.tp
.B per user@host
[jdoe@xyz.com:]checkout:get
.tp
.B per repository
[/path/to/repository:]checkout:edit
.br
[@xyz.com:/path/to/repository:]checkout:get
.br
[jdoe@xyz.com:/path/to/repository:]checkout:edit 
.RE
.SH "SEE ALSO"
.SA config-gui 1
.SA config-logging 1
.\" help://configuration
.\" help://user preferences
.\" help://repository preferences
.SH CATEGORY
.B Overview
.br
.B Admin
