.so ../bk-macros
.TH "bk config" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk config \- show repository configuration information
.SH SYNOPSIS
.B bk config
.SH DESCRIPTION
.LP
The
.B bk config
command is used to display configuration information associated
with a \*(BK repository.  It is not typically used by users.
.LP
XXX - needs update w/ Wayne's config parsing.
.SH "SEE ALSO"
.SA config-etc
.SA config-gui
.SH CATEGORY
.B Admin
