.so ../bk-macros
.TH "bk cmdlog" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk cmdlog \- show the log of commands executed in this repository
.SH SYNOPSIS
.B bk cmdlog
.[B] \-a
.[OPTreq] \-c cutoff
[
.[B] \-v
\ |\ 
.[B] \-\-user
.[B] \-\-date
.[B] \-\-exit
.[B] \-\-version
]
[pattern]
.SH DESCRIPTION
List the history of repository level commands run in repository of
current directory.
Repository level commands are
.BR "bk clone" ,
.BR "bk commit" ,
.BR "bk export" ,
.BR "bk pull" ,
and
.BR "bk push" .
.LP
Commands are listed in least recent to most recent order.
.SH OPTIONS
.TP \-c\*<cutoff\*>
.B \-a
List history of all commands run in the repository, not just repository level
commands.
.tp
.OPTreq \-c cutoff
List commands which happened during the date range specified by
.ARG cutoff .
.tp
.B \-v
List commands in legacy format (verbose).  Implies \-\-user, \-\-date,
\-\-exit and \-\-version options.
.tp
.B \-\-user
List user name.
.tp
.B \-\-date
List (localized) timestamp.
.tp
.B \-\-exit
List exit codes.
.tp
.B \-\-version
List \*(BK version.
.tp
.B pattern
Limit the output to lines matching (regexp) pattern.
.SH EXIT STATUS
.B bk cmdlog
returns exit status 0.
.SH NOTES
The two command logs are maintained by \*(BK in the
.B BitKeeper/log
directory.
.B repo_log
contains all repository level commands ever run in that repository.
.B cmd_log
contains recent commands run in that repository.
.PP
The
.B \-a
option toggles two additional behaviors.  In the absence of the
.BR \-a ,
the optional
.ARG pattern
argument is auto-anchored (has a '^' prepended) and the \*(BK commands
that were spawned as subprocesses of user commands are suppressed.  In
other words, only user commands are listed.
.PP
Commands are logged at the time they start and at
the time they finish.  By default, the output is limited to
the latter.
With the
.B \-v
option, both the start and finish of commands is listed (as well
as other events such as trigger launches).
.SH "SEE ALSO"
.SA range
.SH CATEGORY
.B Repository
