.so bk-macros
.\" help://lclone
.TH "bk clone" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper clone ======================
.SH NAME
bk clone \- create a new copy of a package
.SH SYNOPSIS
.Bc bk clone [\-ql] [
.OPTequal \-E env val
.Bc ] [
.OPTreq \-r rev
.Bc ] [
.OPTopt \-z d
.B ]
.ARG from
.Bc [
.ARG to ]
.SH DESCRIPTION
.LP
The clone command copies from the 
.ARG from
repository and creates a
copy at
.ARG to .
If 
.ARG to 
is not specified then the basename of the
.ARG from
is the implied destination.  This works for fully and partially specified
pathnames as well as BK URLs.
See 
.B bk help url
for further naming information.
.LP
If 
.ARG rev
is specified, the cloned repository will include only
changesets up to and including 
.ARG rev .
.LP
The cloned repository remembers from which repository it was cloned.
The 
.ARG from
repository is known as the "parent", while the newly cloned
repository is known as the "child".
.LP
Subsequent updates to the child can be done by running 
.BR bk\ pull .
Changes made in the child can be pushed back into the parent by running
.BR bk\ push .
.LP
Only completed changesets are cloned.  Any pending deltas are removed
from the child before the clone completes.
.SH OPTIONS
.TP \w'\-E<var>=<x>\ 'u
.OPTequal \-E var x
Export an environment variable to remote \*(BK repository.
.tp
.B \-l
Clone using hardlinks instead of copying the data.  
This is much faster and saves diskspace, but only works 
within a single Unix filesystem.
.tp
.B \-q
Run quietly.
.tp
.OPTreq \-r rev
Clone the repository up to and including cset 
.ARG rev .
A changeset number or changeset key can be used to specify
.ARG rev .
See bk help terms for more information.
.tp
.OPTreq \-z d
Do compression at level 
.ARG d ,
if possible; default is \-z6.
Compression is possible when using ssh or the \*(BK daemon,
but not with rsh.
.SH "SEE ALSO"
.SA bkd 1
.SA parent 1
.SA pull 1
.SA push 1
.SA relink 1
.SA terms 1
.SA triggers 1
.SA url 1
.SH CATEGORY
.B Repository
.br
.B Common
