.so bk-macros
.TH "bk commit" 1 20%E% "\*(BC" "\*(UM"
.\"    ========== Committing changes to a BitKeeper changeset =========
.SH NAME
bk commit \- commit deltas to a changeset
.SH SYNOPSIS
.Bc bk commit [\-adFRq] [
.OPTreq \-S  tag
.Bc ] [
.OPTreq \-y x
.B ]
.br
.Bc bk commit [\-adFRq] [
.OPTreq \-S tag
.Bc ] [
.OPTreq \-Y file 
.Bc ] [\-] 
.SH DESCRIPTION
.LP
This command commits work to a changeset, creating a logical group of
changes which can span multiple files and/or multiple deltas within a
single file.
.LP
The first form will search the repository for any files which are in
"pending" state, i.e., have deltas which do not yet belong to a changeset,
and groups all of them into a changeset.  The second form, typically used
by
.BR "bk citool" ,
takes the list of files to commit from 
.IR stdin .
.LP
You can see what will be added to a changeset when you commit by
running:
.DS
$ bk pending
.DE
Pending lists only files which have checked in deltas; files that
are not yet checked in are not shown.  Use 
.B bk status
if you want to see both.
.LP
Using citool is the best way to commit. Not only will citool help
with checking in files, it will also create a changeset if you enter
ChangeSet comments.  If you must do a command line commit, use:
.DS
$ bk commit
.DE
All revisions which you have checked in will become part of a
changeset.  As part of the commit step, you will be prompted for
comments. The comments should describe the changes that you have made.
It's useful to have the output of 
.B bk pending
in another window to see what you did.
.LP
.B Note:
using the default comments on an import is not advisable.  The default
comments contain information about each file and can create very large
comment entries in the ChangeSet file.  The ChangeSet file is the center
of activity in \*(BK, and having an unnecessarily large one will not help
performance.
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-a
Do not ask the user about logging, fail the commit unless OK.
.tp
.B \-d
Don't run interactively; do the commit with the default comments.
.tp
.B \-F
Force a commit even if no pending deltas.
.tp
.B \-R
Tell commit that it is processing the resync directory.
.tp
.B \-q
Run quietly.
.tp
.OPTreq \-S tag
Tag the tree with
.ARG tag
at the same time as the commit.
.tp
.OPTreq \-Y file
Get check-in comment for changeset from
.ARG file .
.tp
.OPTreq \-y x
Set check-in comment of changeset to
.ARG  x .
.SH "SEE ALSO"
.SA changes 1
.SA citool 1
.SA import 1
.SA pending 1
.SA tag 1
.\" help://changeset
.\" help://changesets
.SH CATEGORY
.B Repository
