.so bk-macros
.TH "bk compatibility" 1 20%E%  "\*(BC" "\*(UM"
.SH NAME
bk compatibility \- Commands compatible between other SCM tools and \*(BK
.SH DESCRIPTION
.LP
\*(BK tries to make a transition from other source control management 
products easier by offering commands commonly used in other products
as aliases to \*(BK commands.
.LP
For example, the following are equivalent in \*(BK:
.DS
bk deledit
bk delta -l
.DE
.SH SCCS
.TP 1i
.B add
Add a file to the repository.  Same as bk delta.
.tp
.B create
Create (initialize) history files.  Same as bk new && bk get.
.\" XXX what is it really?  looks like bk get.  not bk new.  what am i missing?
.tp
.B deledit
Follow a check-in with a locked check-out.  Same as bk delta -l.
.tp
.B delget
Follow a check-in with an unlocked check-out.  Same as bk delta -u.
.tp
.B enter
Add a new file to the repository.  Same as bk new.
.tp
.B sccsdiff
Show differences in revision control files.  Same as bk diffs.
.tp
.B val
Check s.file structure and time stamps.  Same as bk admin -hhhh
.\" XXX I don't know what admin -hhhh does.
.SH RCS
.TP
.B ci
Check in a file.  Same as bk delta.
.tp
.B co
Check out a file.  Same as bk edit.
.SH "SEE ALSO"
.SA delta 1
.SA diffs
.SA get 1
.SA new 1
.SA admin 1
.SH CATEGORY
.B Compat
