.so bk-macros
.TH "bk c2r" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk c2r \- convert changeset revision to file revision
.SH SYNOPSIS
.B bk c2r 
.OPTreq \-r rev 
\ 
.ARG file 
.SH DESCRIPTION
This command takes a changeset revision and a filename and prints the
latest revision in the file that in included in that changeset.
.SH "SEE ALSO"
.SA r2c 1
.SH CATEGORY
.B Utility
