.so bk-macros
.TH "bk csettool" 1 20%E% "\*(BC" "\*(UM"
.\"    =============== BitKeeper Graphical ChangeSet Browser ===============
.SH NAME
bk csettool \- \*(BK graphical changeset browser
.SH SYNOPSIS
.Bc bk csettool [
.OPTreq \-r revs
.Bc ] [
.OPTreq \-f file@rev
.B ]
.SH DESCRIPTION
.LP
csettool is used to view detailed information about the specified
changeset[s].  csettool displays the list of changes in each changeset,
the ChangeSet history, and the differences found in each file contained
in each changeset.
.LP
Csettool is a very useful aide when tracking down bugs. For example,
when using
.B revtool
to view comments for a specific file inorder to track when a change
was made to the file. Once the desired file is found, the user can
then click on the "View changeSet" button in
.B revtool
to bring up csettool to see what other files were modified at the
same time that the file of interest was modified.
.LP
To see the changes for a particular file, click on the file name
in the top left window and you will see:
.TP 2
\*(BU
the number of diffs in the middle status window
.tp
\*(BU
the old version of the file in the lower-left window
.tp
\*(BU
the new version of the file in the lower-right window
.tp
\*(BU
the ChangeSet's comments followed by the delta's comments in
the upper-right window
.LP
Use the space bar to move between diffs and files.  Each time you
hit the space bar, the next diff is brought into view.  If you are
on the last diff, the tool moves to the next file. The Next (>>)
buttons and Previous (<<) buttons in the top menu bar will also
allow you to browse the files and diffs.
.LP
The
.B History
button in the menu bar can be used to start the graphical history
browser, revtool, on either the entire project (ChangeSet file)
or on the file highlighted in the upper-left window.
.SH OPTIONS
.TP
.OPTreq \-r revs
ChangeSet revision to examine. Can be a single revision or a range of 
revisions. If no -r option is given, 
.B csettool
defaults to -r+, i.e. the most recent changeset.
.TP
.OPTreq \-f file@rev
Given a filename and revision,
.B csettool
starts up with the specified file and revision selected.
.SH BINDINGS
.TP 16
.B Home
Scroll both files to the top
.tp
.B End
Scroll both files to the bottom
.tp
.B PageUp
Scroll both files one screen up
.tp
.B PageDown
Scroll both files one screen down
.tp
.B
UpArrow
Scroll both files one line up
.tp
.B DownArrow
Scroll both files one line down
.tp
.B LeftArrow
Scroll both files to the left
.tp
.B RightArrow
Scroll both files to the right
.TP
.B Alt-UpArrow
Make the diffs windows one line bigger and
the lists windows one line smaller.
.tp
.B Alt-DownArrow
Make the diffs windows one line smaller and
the lists windows one line bigger.
.TP
.B Control-q
Quit
.tp
.B space
Next diff, if last diff in this file, then goto next file
.tp
.B n
Next diff, if last diff in this file, then goto next file
.tp
.B p
Previous diff, if first diff in this file, then goto previous file
.tp
.B .
Center the current diff on the screen
.tp
.B N
Next file
.tp
.B P
Previous file
.tp
.B Double-Clicking
Double clicking the left mouse button on a file in the file list brings 
up revtool for the specified file.
.tp
.B MouseWheel
Move wheel towards you to view next diff and away from you to view previous 
diff
.SH "FUTURE DIRECTIONS"
.LP
We plan on having a single screen diff window option where the changes
are all shown color coded in one window.  
.SH "SEE ALSO"
.SA cset 1
.SA difftool 1
.SA revtool 1
.SA ranges 1
.SH CATEGORY
.B GUI-tools
.br
.B Repository
