.so ../bk-macros
.TH "bk c2r" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk c2r \- convert changeset revision to file revision
.SH SYNOPSIS
.B bk c2r 
.OPTreq \-r cset_rev
.ARG file
.SH DESCRIPTION
This command takes a changeset revision and a filename and prints the
latest revision in the file that is part of that changeset.
.SH EXAMPLE
Suppose that revision 1.5 of \f(CWfoo.c\fP was made in changeset 1.1234.
.DS
$ bk c2r -r1.1234 foo.c
1.5
$ bk log -r1.5 foo.c
foo.c 1.5
  2009-07-07 11:20:27-07:00 wscoot@desk.bitkeeper.com +4 -3
  Include system.h.
.DE
This command is the inverse of
.BR "bk r2c" ,
which goes from a file to a changeset revision.
This goes the other way, from changeset to file revision.
This command is here for completeness only, you can get the same effect
in a single step like so:
.DS
$ bk log -r@1.1234 foo.c
foo.c 1.5
  2009-07-07 11:20:27-07:00 wscoot@desk.bitkeeper.com +4 -3
  Include system.h.
.DE
.SH "SEE ALSO"
.SA r2c
.SH CATEGORY
.B Utility
