.so ../macros
.TH "bk cset" 1 08/18/00 "*(BC" *(BK
.\"    ====================== BitKeeper cset command ======================
.SH NAME
bk cset \- creates and manipulates changesets
.SH SYNOPSIS
.if t \{\
.B cset 
.OA [\-CcHhpq] 
.OA d range
.OA i list
.OA l range
.OA M range
.OA m range
.OA r range
.OA S sym
.OA x list
.OA Y file
.OA y msg 
.\}
.if n
bk cset [\-CcHhpq] [-d<range>] [i<list>] [l<range>] 
[-M<range>] [-m<range>] [-r<range>] [-S<sym>] [-x<list>] [-Y<file>] [-y<msg>]
.SH DESCRIPTION
.LP
The cset command is a low level command used to generate BitKeeper patches.
.SH OPTIONS
.TP
.B \-C
Clear and remark all ChangeSet boundries.
.TP
.B \-c
Like \-m, except generate only ChangeSet diffs.
.TP
.AN \-d range
Do unified diffs for the range,
.IR range .
.TP
.B \-H
With \-r listing, hide Changeset file from file list.
.TP
.B \-h
With \-r listing, show historic path.
.TP
.AN \-i list
create a new cset on TOT that includes the csets in
.IR list .
.TP
.AN \-l range
List each rev in 
.I range 
as file@rev (may be multiline per file).
.TP
.AN -M range
Mark the files included in the range of csets.
.TP
.AN \-m range
Generate a patch of the changes in
.IR range .
.TP
.B \-p
Print the list of deltas being added to the cset.
.TP
.B \-q
Run quietly.
.TP
.AN \-r range
List the filenames:rev..rev which are included in
.IR range .
.TP
.AN \-S sym
Set
.I sym
to be a symbolic tag for this revision.
.TP
.AN \-x list
Create a new cset on TOT that excludes the csets in 
.IR list .
.TP
.AN \-Y file
Sets the changeset comment to the contents of
.IR file .
.TP
.AN \-y msg
Sets the changeset comment to 
.IR msg .
.SH BUGS
.LP
This command does too much and needs to be split apart.
Many of these options are going away, to be replaced by the rset command.

.SH CATEGORY
.B Repository
