.so ../bk-macros
.TH "bk csets" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk csets \- run changes or csettool on last set of incoming changes
.SH SYNOPSIS
.B bk csets
.[B] \-\-stats
.[B] \-DTv
.SH DESCRIPTION
.LP
The
.B csets
command will run the
.B bk csettool
command on the last set of 
changesets imported into this repository with a
.BR bk\ pull ,
or
.BR bk\ push .
This is useful for tracking down problems and/or doing a quick review.
.SH OPTIONS
.TP \-\-stats
.B \-D
Use 
.B bk difftool
(gui mode) or
.B bk diffs -pu
(text mode) to display the changesets.
If there were many pulled in, perhaps with changes added and then deleted
as part of a review, viewing the difference between the start and the end
points may be less "noisy".
.tp
.B \-\-stats
Print a statistics header like diffstat.
.tp
.B \-T
Use 
.B bk changes
to display the changesets (text mode).
.tp
.B \-v
Pass
.Q \-v
to
.BR "bk changes" .
.SH BUGS
The
.Q \-T
option should be implied if there is no graphical display to be found.
.SH "SEE ALSO"
.SA changes
.SA csettool
.SA pull
.SA push
.SH CATEGORY
.B Repository
