.so ../bk-macros
.TH "bk cp" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk cp \- create a copy of a file preserving its revision history
.SH SYNOPSIS
.\"
.B bk cp 
.ARG oldfile
.ARG newfile
.SH DESCRIPTION
.LP
Use bk cp to copy an existing file and its revision history to a new file.
The new file will have a changed root identifier so that it is a different
inode.  The new file will be distinct from the old file moving forward,
but will have the revision history from the old file preserved.
.\"XXX should i be explicit in saying the old file will get updates from
.\" the file in other repos or is this enough?
.SH "SEE ALSO"
.SA mv 1
man cp
.\" help://copy
.SH CATEGORY
.B File
