.so ../macros
.TH "bk cmdlog" 1 08/18/00 "*(BC" *(BK
.\"    =================== BitKeeper Command Log ===================
.SH NAME
bk cmd_log \- show the log of commands executed in this repository
.SH SYNOPSIS
.B bk cmdlog
.br
.B bk cmdlog \-a
.SH DESCRIPTION
.LP
There are two command logs maintained by BitKeeper, both in the
BitKeeper/log directory: repo_log and cmd_log.  The first logs only
commands which operate at the repository level, specifically:
.RS .5i
clone
.br
commit
.br
export
.br
pull
.br
push
.RE
The second logs all other commands.
To see the repository commands, run
.AX
bk cmdlog
.XA
To see all commands, run
.AX
bk cmdlog -a
.XA
Commands are listed in least recent to most recent order.
.SH CATEGORY
.B Repository
