.so bk-macros
.TH "bk cmdlog" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== BitKeeper Command Log ===================
.SH NAME
bk cmdlog \- show the log of commands executed in this repository
.SH SYNOPSIS
.B bk cmdlog [\-a]
.SH DESCRIPTION
.LP
List the history of repository level commands run in
repository of current directory.  Repository level commands are
clone, commit, export, pull, and push.
.LP
Commands are listed in least recent to most recent order.
.SH OPTIONS
.TP
.B \-a
List history of all commands run in the repository, not just repository level
commands.
.TP
.OPTopt \-c cutoff
List commands which happened during the date range specified by
.ARG cutoff .
.SH NOTES
The two command logs are maintained by \*(BK in the \*(BK/log directory.
repo_log contains repository level commands run in a repository.
cmd_log contains all commands run in a repository.
.SH "SEE ALSO"
.SA range 1
.SH CATEGORY
.B Repository
