.so ../bk-macros
.TH "bk cset" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper cset command ======================
.SH NAME
bk cset \- creates and manipulates changesets
.SH SYNOPSIS
.Bc bk cset [\-Cpq] [
.OPTreq \-i list
.Bc ] [
.B \-l
.Bc ] [
.OPTreq \-M range
.Bc ] [
.OPTreq \-r rev
.Bc ] [
.OPTreq \-S sym
.Bc ] [
.OPTreq \-x list
.Bc ] [
.OPTreq \-Y file
.Bc ] [
.OPTreq \-y msg
.B ]
.SH DESCRIPTION
.LP
The cset command is a low level command used mostly to generate \*(BK patches.
.SH OPTIONS
.if t .TP .7i
.if n .TP 1i
.B \-C
Clear and remark all ChangeSet boundaries.
.tp
.OPTreq \-i list
create a new cset on TOL that includes the csets in
.ARG list .
.tp
.B \-l
Read changeset revisions or keys from stdin and print the list of deltas in 
each of the changesets.
.tp
.OPTreq \-M range
Mark the files included in the
.ARG range
of csets.
.tp
.B \-p
Print the list of deltas being added to the cset.
.tp
.B \-q
Run quietly.
.tp
.OPTreq \-r rev
Print the list of deltas in ChangeSet revision,
.ARG rev .
.tp
.OPTreq \-S sym
Set
.ARG sym
to be a symbolic tag for this revision.
.tp
.OPTreq \-x list
Create a new cset on TOL that excludes the csets in 
.ARG list .
.tp
.OPTreq \-Y file
Sets the changeset comment to the contents of
.ARG file .
.tp
.OPTreq \-y msg
Sets the changeset comment to 
.ARG msg .
.SH BUGS
.LP
This command does too much and needs to be split apart.
.SH CATEGORY
.B Repository
