.so bk-macros
.TH "bk diffs" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk diffs \- show differences in revision controlled files
.SH SYNOPSIS
.Bc bk diffs [\-bBcDfhMnpsuUvw] [
.OPTreq \-C rev
.Bc ] [
.OPTreq \-d date
.Bc ] [
.OPTreq \-r r
.Bc ] [
.OPTreq \-R r
.B ]
.BKARGS
.SH DESCRIPTION
.LP
To view changes you have made to all of the files in a directory
since checking the files out, type:
.DS
$ bk diffs | more
.DE
To see the changes for all files in your tree, do the following:
.DS
$ bk \-r diffs | more
.DE
The 
.B bk diffs
command supports context, unified, procedural, and side-by-side diffs.
All of the above can be optionally annotated with author, date, and/or
revision numbers.
.LP
You can also diff specific revisions. For example:
.DS
$ bk diffs -r1.2..1.4 foo.c
.DE
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-b
Ignore changes in amount of white space.
.tp
.B \-B
Ignore  changes  that  just  insert or delete blank lines.
.tp
.B \-c
Do context diffs.
.tp
.OPTreq \-C rev
Show all changes made by changeset containing rev 
.ARG rev .
.tp
.B \-D
Prefix lines with dates.
.tp
.OPTreq \-d date
Diff using date or symbol.
.tp
.B \-f
Prefix lines with file names.
.tp
.B \-h
Don't print headers.
.tp
.B \-M
Prefix lines with revision numbers.
.tp
.B \-n
Do RCS style diffs.
.tp
.B \-p
Procedural diffs, like
.B diff \-p.
.tp
.OPTreq \-r rev
Diff revision 
.ARG rev .
.tp
.OPTreq \-R rev
Show diffs between parent of 
.ARG rev
and
.ARG rev .
.tp
.B \-s
Display side-by-side diffs.
.tp
.B \-U
Prefix lines with user names.
.tp
.B \-u
Do unified diffs.
.tp
.B \-v
Be verbose about non-matching ranges.
.tp
.B \-w
Ignore white space when comparing lines.
.SH SEE ALSO
.BR diff (1)
.br
.SA difftool 1
.SA export 1
.SA treediff
.\" help://differences
.\" help://sdiffs
.SH CATEGORY
.B File
.br
.B Common
