.if \n[NESTED] \{\
.so ../bk-macros
.TH "bk detach" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk detach \- create a stand-alone clone of a component repository
.SH SYNOPSIS
bk detach
.[B] \-q
.[OPTreq] \-B url
.[OPTequal] \-E e v
.[OPTreq] \-r rev
.ARG component
.[ARG] to
.SH DESCRIPTION
The 
.B bk detach
command is a form of
.BR "bk clone"
used to create a stand-alone clone of a component repository.
.LP
.SH OPTIONS
.TP \-E\*<env\*>=\*<val\*>
.OPTreq \-B url
Set the BAM server url to 
.ARG url
in the destination repository.
.tp
.OPTequal \-E env val
Export an environment variable to the 
.B bkd
running in the remote \*(BK repository.
Typically used to pass information to remote triggers.
Only variables with the prefix
.V BKU_
are allowed.
.tp
.B \-q 
Run quietly.
.tp
.OPTreq \-r rev
Clone the repository up to and including cset 
.ARG rev .
A changeset number or changeset key can be used to specify
.ARG rev .
.SH SEE ALSO
.SA attach
.SA clone
.SA port
.SA setup
.SH CATEGORY
.B Nested
.\}
