.so bk-macros
.TH "bk difftool" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk difftool \- \*(BK Graphical Diff Tool
.SH SYNOPSIS
.B bk difftool
.br
.B bk difftool -
.br
.B bk difftool
.ARG file1
.br
.B bk difftool 
.OPTreq \-r rev
\ 
.ARG file1
.br
.B bk difftool
.OPTreq \-r rev1
\ 
.OPTreq \-r rev2
\ 
.ARG file1
.br
.B bk difftool
.ARG file1
.ARG file2
.SH DESCRIPTION
.LP
The
.B difftool
command is a side-by-side differences viewer that shows each
file in a separate window, with the differences color coded.
You can move back and forth through the diffs using the keys
described below.
All differences are highlighted, but as you move to a new diff,
that diff becomes highlighted in a bold font.
.SH ARGUMENTS
.LP
If no arguments are given, 
.B difftool
finds all the modified files in the current directory and
subdirectories and allows the user to select the files they are
interested in via a pull-down menu. Also, keyboard accelarators can
be used to navigate between the files.
.LP
If a dash (-) is given as an argument, 
.B
difftool
takes a list of files to view from stdin. For example, bk sfiles -gc | bk difftool -
.LP
If only one file is specified and that file is a locked and modified file,
.B difftool
will diff the most recent revision against the locked version.
.LP
If a revision and a checked out file are specified
.B difftool
diffs that version against the checked out file.
.LP
If two revisions and a file are specified
.B difftool
diffs those two versions of the file.
.LP
If two files are specified,
.B difftool
diffs those two files.
.SH "KEY BINDINGS"
.TP 1.2i
.B Home
Scroll both files to the top
.tp
.B End
Scroll both files to the bottom
.tp
.B PageUp
Scroll both files one screen up
.tp
.B PageDown
Scroll both files one screen down
.tp
.B UpArrow
Scroll both files one line up
.tp
.B DownArrow
Scroll both files one line down
.tp
.B Left
Scroll both files to the left
.tp
.B Right
Scroll both files to the right
.TP
.B Control-q
Quit
.tp
.B space
Next diff
.tp
.B n
Next diff
.tp
.B p
Previous diff
.tp
.B .
Center the current diff on the screen
.tp
.B Control-N
Go to then next file
.tp
.B Control-P
Go to the previous file
.SH SEE ALSO
.LP
.SA diffs 1
.SA fmtool 1
.SH CATEGORY
.B GUI-tools
