.so ../bk-macros
.TH "bk delta" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk delta \- check in modified files
.SH SYNOPSIS
.B bk delta
.[B] \-acflpqu
.[OPTreq] \-D file
.[OPTreq] \-y msg
.[OPTreq] \-Y file
.BKARGS
.SH DESCRIPTION
.LP
The
.B bk delta 
command is used to check in changes made to revision controlled files.
This command is fairly rich in features and is the preferred interface
for scripting.  For interactive checkins, 
.B "bk citool" 
is the preferred interface.
.SH OPTIONS
.TP \-y\*<comment\*>
.B \-a
Normally, 
.B delta
is used to modify existing files.
This option changes delta to act like bk new for new files and bk delta
for existing files.
The usefulness of this option is more apparent when you consider having
a mixed list of files, some under revision control and some not.
.tp
.B \-c
Take checkin comments from 
.BI SCCS/c. filename\fR.
It is an error if the c.file does not exist.
.tp
.OPTreq \-D file
Take diffs from
.if t .IR file .
.if n <file>.
.tp
.B \-f
Force the creation of a null delta even if there are no changes to the file.
.tp
.B \-l
Follow check in with a locked check out like
.QR "bk get \-e" .
.tp
.OPTreq \-M mode
Set the permissions on the new delta to
.if t .IR mode .
.if n <mode>.
More commonly used with bk new.
.tp
.B \-p
Print differences before prompting for comments.
.tp
.B \-q
Run silently.
.tp
.B \-u
Follow check in with an unlocked check out like bk get.
.tp
.OPTreq \-Y file
Use the comment specified in 
.ARG file
for comments for all files.
.tp
.OPTreq \-y comment
Sets the revision comment to 
.if t .IR comment .
.if n <comment>.
.SH BUGS
The format of the init file is not documented.
.SH "SEE ALSO"
.SA citool
.SA edit
.SA get
.SA new
.SH CATEGORY
.B File
