.so ../bk-macros
.TH "bk editor" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk editor \- automatically check out \*(BK files when using $EDITOR
.SH SYNOPSIS
.B bk editor
.ARG file
.SH DESCRIPTION
.LP
.B bk editor
is used as a shortcut to edit a file whether or not it is a \*(BK file.
If the file is under revision control,
.B bk editor
will
.B bk edit
the file then exec the editor of choice on that file.  If the
file is not under revision control, it will exec the editor on that file.
.LP
The
.V $EDITOR
environment variable must be set to the editor of 
your choice.
.LP
bk editor can be used as follows:
.DS
bk editor foo.c
.DE
Another method is to set the
.V $EDITOR
environment variable and alias
the editor name to 
.B bk editor
Using xemacs as an example, set
.V $EDITOR
and then alias:
.DS
EDITOR=xemacs
alias xemacs='bk editor'
.DE
To open the file for editing:
.DS
xemacs foo.c
.DE
.SH CATEGORY
.B Compat
