.so ../bk-macros
.TH "bk extras" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    ======================= Finding extra files =======================
.SH NAME
bk extras \- list extra files not under revision control
.SH SYNOPSIS
.B bk extras 
.[B] \-a
.[ARG] dir
.SH DESCRIPTION
.LP
The
.B bk extras
command finds files which are not under revision control and 
are not listed in the ignore file.
.LP
The default behavior is to find all extra files in the entire tree; this
can be changed by specifying a subdirectory like so
.DS
bk extras .
.DE
The default behavior is to respect the ignore file; this can be changed
by adding the
.Q \-a
flag like so
.DS
bk extras -a    # find all extra files in entire repo
bk extras -a .  # find all extra files at or below "."
.DE
.\" XXX need OPTIONS section?
.SH "SEE ALSO"
.SA ignore
.SA gfiles
.SH CATEGORY
.B File
