.so bk-macros
.TH "bk edit" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk edit \- check out a file for editing (writable)
.SH SYNOPSIS
.B bk edit [-q]
.BKARGS
.SH DESCRIPTION
.LP
Use
.B edit
when modifying existing files. 
.B Edit
checks the file out of the SCCS directory in a read-write mode
and locks the file for modifications.
.LP
.B Edit
with no options will check out all files in a directory.
.SH OPTIONS
.TP
.B \-q
run quietly
.SH NOTE
.B edit
is actually an alias for
.B bk get \-e
.SH SEE ALSO
.SA co 1
.SA get 1
.SA new 1
.SH CATEGORY
.B Basics
