.so bk-macros
.\" XXX -t is listed in synopsis, but not in options
.TH "bk export" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk export \- checks out clear-text version of all \*(BK files
.SH SYNOPSIS
.B bk export \-tpatch [\-hT] [\-d u|c]
.OPTreq \-r rev1,rev2
.br
.Bc bk export [\-tplain] [\-kTvw] [
.OPTreq \-i pat
.Bc ] [
.OPTreq \-x pat
.B ]
.OPTreq \-r rev
.Bc \ [
.ARGc source
.B ]
.ARG dest
.SH DESCRIPTION
.LP
The
.B export
command generates a directory tree alongside the \*(BK
repository which contains checked-out copies of all the files under
\*(BK control.  It can also generate traditional
.RB ( diff
.BR \-urN )
patches between any two revisions of the source tree.
By default, bk export only exports user files.  Files under
the BitKeeper directory are not exported.  This behaviour can be
changed with the -i and -x options.
.LP
If you are trying the export a patch for a sub-directory, and
some of the files in that directory have been moved out of the
directory. You want to make sure the out-of-view file looks
like deleted file. This is done by replacing the @rev part of 
the out-of-view file to @1.0. You can do this using the following command:
.DS
bk rset -rA,B | your_script | bk gnupatch 
.DE
.SH OPTIONS
.if t .TP
.if n .TP 1i
.OPTreq \-d u|c
Set patch's diff style to unified or context diff.  If no style
specified, do regular diffs.
.tp
.B \-h
Disable patch header.
.tp
.OPTreq \-i pat
Export only pathnames matching 
.ARG pat
pattern.
.tp 
.B \-k
Do not expand keywords (default is to expand keywords).
.tp
.OPTreq \-r rev
Export the tree as of revision 
.ARG rev .
.tp
.B \-T
Set gfile modification time to check-in time.
.tp
.OPTreq \-t type
Select export format via 
.ARG type :
.RS .4i
.tp
.B plain 
export file in plain text to a directory tree. 
.tp
.B patch 
export file in gnu patch format.
.RE
.tp
.B \-v
Be verbose.
.tp
.B \-w
Make files writable (default is read-only).
.tp
.OPTreq \-x pat
Export all pathnames not matching 
.ARG pat
pattern.
.LP
Note that
.I \-i
and
.I \-x
take a single,
.BR egrep \-style
regular expression which is matched against the partial pathname from the root.
.LP
.SH SEE ALSO
.BR diff (1)
.br
.SA gnupatch 1
.SA rset 1
.SH CATEGORY
.B Compat
