.so ../bk-macros
.TH "bk fast-export" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk fast-export \- export the repository in a format compatible with git
.SH SYNOPSIS
.B bk fast-export
.[B] \-\-no\-bk\-keys
.[OPTreq] \-\-branch= branch
.SH DESCRIPTION
bk fast-export exports the entire repository in a format suitable for
input to git's fast-import command. The output is sent to standard
output.
.LP
By default the BitKeeper MD5KEY of the equivalent changeset will be
added to every commit in git.
.SH OPTIONS
.TP \-\-branch=<branch>
.B \-\-no\-bk\-keys
Don't add the "bk: <mk5key>" line at the end of the comments.
.tp
.OPTreq \-\-branch= branch
By default the export will be done for the "master" git branch. This option
lets you do the export for a different branch. This is useful for
exporting two different BitKeeper branches (e.g. "dev" and "stable")
into the same git repository. See CAVEATS below.
.tp
.B \-S
.tp
\-\-standalone
When used in a nested collection, export only the product or the 
component implied by the current working directory.
.SH EXAMPLE
.LP
The commands to export a BitKeeper repository named
"bk-repo" to a git repository named "git-repo"
would be:
.DS
$ git init git-repo
$ (cd bk-repo; bk fast-export) | (cd git-repo ; git fast-import)
.DE
.SH CAVEATS
.LP
It's possible to run the exporter over different BitKeeper
repositories and use the same git repository as a destination. All the
shared history will be imported by git only once as long as the
repositories have identical comments and matching gone files. 
.LP
It's probably a good idea to contact BitKeeper support if you are
going to be doing this.
.SH EXIT STATUS
.LP
.B bk fast-export
returns exit status 0 if the export completed successfuly. Non-zero if
there was an error.
.SH CATEGORY
.\" If you change this you need to go make the code in help.c match
.B Utility
