.so ../bk-macros
.TH "bk filetypes" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME 
bk filetypes \- summary of \*(BK file types
.SH DESCRIPTION
.LP
For each file under revision control, there are a number of files
associated with the main file.  
The following list describes the purpose of each file:
.TP \fBSCCS/s.\|\fP\*<foo\*>
.ARG foo
\*(lqgfile\*(rq \- the \*(lqgotten\*(rq file; this is your source file
.\"this is your source file (aka "gotten" file)
.tp
.OPTreq SCCS/s.\| foo
\*(lqsfile\*(rq \-
the revision history of all versions of the gfile
.tp
.OPTreq SCCS/x.\| foo
\*(lqxfile\*(rq \- a temporary file which contains the new version
of the sfile under construction.  When the check-in is
finished, the sfile is removed and the xfile is moved
into its place.
.tp
.OPTreq SCCS/c.\| foo
\*(lqcfile\*(rq \- a temporary copy of check in comments,
currently used only by
.BR "bk citool" .
.tp
.OPTreq SCCS/d.\| foo
\*(lqdfile\*(rq \- a temporary file that indicates there is at least one
pending delta in the sfile.
.SH FUTURE DIRECTIONS
Other than the gfile, accessing any of these files directly is discouraged.
In the future, all of the meta-files will be \fBvirtual\fR.  At that point,
there will be interfaces to read them, test for their presence, and
write them.
.SH CATEGORY
.B Overview
.br
.B File
.\" help://File/filetype
.\" help://File/gfile
.\" help://File/sfile
.\" help://File/pfile
.\" help://File/cfile
.\" XXX Are the following references correct?
.\" help://File/s.file
.\" help://File/p.file
.\" help://File/c.file
.\" help://File/x.file
.\" help://File/z.file
