.so ../bk-macros
.TH "bk fix" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk fix \- re-edit a checked in (but uncommitted) delta
.SH SYNOPSIS
.B bk fix [-v]
.ARG file.c
.br
.B bk fix -c [-v]
.SH DESCRIPTION
.LP
The
.B fix
command allows you to revise changes made to the most recent delta
in a file.  Typically, this feature is used immediately after a check in
when it is realized that that delta was not done or was incorrect.
.LP
In general,
only deltas which have not yet been committed to a changeset may be modified.
The reason for this is that changesets are immutable - once they are created,
they may not be modified.
.LP
In some cases, it is useful to be able to "uncommit" an entire changeset.
If, and only if, you are positive that there are no other copies of this
changeset in other repositories, then use
.B bk fix -c
which will fix all deltas in the most recent changeset.  It is not an error
if there are other copies of the changeset, it just means you will have
to merge the two versions of the same change.
.LP
The checkin comments are preserved if the subsequent check is made bi
.B bk citool.
.SH OPTIONS
.TP
.B \-c
fix an entire changeset.
.tp
.B \-v
be verbose.
.SH BUGS
Symbolic tags are not preserved.
.SH SEE ALSO
.LP
.SA ci 1
.SA edit 1
.SA stripdel 1
.SH CATEGORY
.B File
