.so ../bk-macros
.TH "bk flags" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk flags \- show a listing of files and their \*(BK flags
.SH SYNOPSIS
.B bk flags
.BKARGS
.SH DESCRIPTION
.LP
Displays a listing of files and their \*(BK flags in the following format:
.DS
foo.c  BITKEEPER,CSETMARKED,EXPAND1,SCCS
.DE
The flags are described on the 
.B bk admin
man page.
.SH "SEE ALSO"
.SA admin
.SA log
.SH CATEGORY
.B Admin
