.so ../bk-macros
.TH "bk flags" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk flags \- show a listing of files and their \*(BK flags
.SH SYNOPSIS
.B bk flags
.BKARGS
.SH DESCRIPTION
.LP
Displays a listing of files and their \*(BK flags in the following format:
.DS
foo.c  BITKEEPER,CSETMARKED,EXPAND1,SCCS
.DE
.SH "SEE ALSO"
.SA admin 1
.SA prs 1
.SH CATEGORY
.B File
