.so ../bk-macros
.TH "bk findkey" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk findkey \- look for keys in files
.SH SYNOPSIS
.B bk findkey [opts | key] 
.BKARGS
.SH DESCRIPTION
.B bk findkey
may be used to look for keys in one or more files.  In \*[BK], keys
are the internal names for files and/or file deltas.  
.LP
The keys may be either the long form or the MD5 form (see 
.BR "bk log" ).
You may search for keys using only a portion of the key as described
below.
Each delta in each file that matches all specified parts is listed.
.SH OPTIONS
.TP \-b\*<random\*>
.OPTreq \-b random
specify the random bits part of a key.
.tp
.OPTreq \-c chksum
specify the checksum part of a key.
.tp
.OPTreq \-e email
specify the user@host.domain part of a key.
.tp
.OPTreq \-h h.dom
specify the host.domain part of a key.
.tp
.OPTreq \-p path
specify the path part of a key.
.tp
.OPTreq \-t utc
specify the timestamp part of a key.  Date formats accepted are
either
.I yyyymmddhhmmss
or
.IB yyyy /\c
.IB mm /\c
.IB "dd\ hh" :\c
.IB mm :\c
.IB ss .
.tp
.OPTreq \-u user
specify the username part of a key.
.SH "SEE ALSO"
.SA log
.SH CATEGORY
.B Utility
