.so ../bk-macros
.TH "bk gca" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk gca \- show the greatest common ancestor
.SH SYNOPSIS
.B bk gca
.OPTreq \-r rev1
.OPTreq \-r rev2
.ARG file
.SH DESCRIPTION
This command will print the revision which is the greatest common
ancestor (GCA) of the specified two revisions.
If there is no node in the graph which is an exact match, the
printed revision will have an include list and/or an exclude list
of revisions which must be added to the revision in order to get
the actual GCA.
.SH OPTIONS
.TP \-r\*<rev\*>
.OPTreq \-r rev
specify the first and second rev (both are required).
.SH CATEGORY
.B Utility
