.so ../bk-macros
.TH "bk gethost" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk gethost \- display machine name
.SH SYNOPSIS
.B bk gethost
.[B] \-nr
.SH DESCRIPTION
.LP
Outputs the fully-qualified name of the machine.
Used primarily when doing \*[BK] scripting.
.OPTIONS
.TP
.B \-n
print the internet address instead of the host
.TP
.B \-r
print the real host name, ignoring
.V $BK_HOST .
.SH NOTES
On some UNIX systems, it can happen that \*[BK] will output an error
message complaining that localhost is an invalid hostname.  Often the
fix is to simply add a fully qualified hostname to /etc/hosts.  For
example:
.IP
::1	localhost6 yourhost.yourdomain.com
.SH SEE ALSO
.SA getuser
.SH CATEGORY
.B Utility
.\" help://hostname
