.so bk-macros
.TH "bk get" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== Editing BitKeeper files ===================
.SH NAME
bk get \- check out \*(BK files
.SH SYNOPSIS
.Bc bk get [\-aCdDeFkmnNpqu] [
.OPTreq -G name
.Bc ] [
.OPTreq \-i list
.Bc ] [
.OPTreq \-r rev
.Bc | 
.OPTreq \-c date
.Bc ] [
.OPTreq \-x list
.B ]
.BKARGS
.SH DESCRIPTION
.LP
.B get
is used to check out files for viewing or building. By default,
files are checked out unlocked and in a read-only mode.  The
.B get
command is used primarily within automated scripts and is not the
preferred method for checking out files for editing.  To check out
files for editing, see bk edit.
.LP
You do not need to check out every file in order to compile your
program since most versions of the Make program will check files out
as they are needed. In order for this to work, the get command needs
to be in your path and the dependencies need to be correct in the
Makefile.  If that is true, a simple "make" will check out and 
build your product.
.SH OPTIONS 
.if t .TP .6i
.if n .TP 1i
.B \-a
Align prefix output in a human readable form.
Used with one of the following options [mNnud].
.tp
.OPTreq \-c date
Get the latest revision before 
.ARG date .
.tp
.B -C
implictly specifies a revision which is the most recent revision committed
to a changeset.
.tp
.B \-d
Prefix each line with the date of last modification.
.tp
.B -D
Output a diff.
.tp
.B -DD
Output cset diffs.
.tp
.B -DDD
Output hash diffs.
.tp
.B \-e
Get file for editing. A lock is placed on the s.file.
.tp
.B -F
Do not verify the file checksum.
.tp
.B \-g
Suppress the retrieval of any text.
.tp
.OPTreq \-G name
Place the checked out file in 
.ARG name 
instead of the default gfile location.
.tp
.B -h
Invert sense of file's hash flag.
.tp
.B -H
Put file in its historic location.
.tp
.OPTreq \-i list
Include revs in 
.ARG list .
.tp
.B \-k
Don't expand RCS or SCCS keywords. \-k is implied by \-e.
.tp
.B \-m
Prefix each line with the revision of last modification.
.tp
.OPTreq \-M rev
Merge with 
.ARG rev .
.tp
.B \-n
Prefix each line with the filename.
.tp
.B \-N
Prefix each line with its line number.
.tp
.B \-p
Write file to standard output (useful in scripts).
Required with \-r
.ARG rev 
where 
.ARG rev 
is anything other than the most recent delta.
.tp
.B -P
Write to stdout, force get; useful for corrupted files.
.tp
.B \-q
Run quietly.
.tp
.B -R
Rev is part of pathname, i.e., 
.BR src/get.c@1.102 .
.tp
.OPTreq \-r rev
Get this revision.
.tp
.B \-S
If a gfile exists, don't check it out again.
.tp
.B \-T
Set the gfile's modification time to the delta's
creation time.
.tp
.B \-u
Prefix each line with the user who last modified it.
.tp
.OPTreq \-x list
Exclude revs in 
.ARG list .
.SH "SEE ALSO"
.SA co 1
.SA edit 1
.SA exclude 1
.SA include 1
.SH CATEGORY
.B File
