.so ../macros
.TH "bk get" 1 08/18/00 "\*(BC" "\*(UM"
.\"    =================== Editing BitKeeper files ===================
.SH NAME
bk get \- check out BitKeeper files
.SH SYNOPSIS
.if t \{\
.B bk get [\-qkepdmunN] [-G
.IB name ]
.B [\-r
.IB rev | 
.BI \-c date
.B ] [
.IB files... | 
.IB \- ]
\}
.if n \{\ 
bk get [-qkepdmunN] [-G<name>] [-r<rev> | -c<date>] [files... | -]
\}
.SH DESCRIPTION
.LP
get is used to check out files for viewing or building. By default,
files are checked out unlocked and in a read-only mode.  The get
command is used primarily within automated scripts and is not the
preferred method for checking out files for editing.  To check out
files for editing, see bk edit.
.LP
You do not need to check out every file in order to compile your
program since most versions of the Make program will check files out
as they are needed. In order for this to work, the get command needs
to be in your path.
.SH OPTIONS 
.if t .TP
.if n .TP 1i
.B \-a
Align prefix output in a human readable form.
Used with one of the following options [mNnud].
.tp
.AN \-c date
Get the latest revision before the 
.IR date .
.tp
.B -D
Output a diff.
.tp
.B -DD
Output cset diffs.
.tp
.B -DDD
Output hash diffs.
.tp
.B \-d
Prefix each line with the date of last modification.
.tp
.B \-e
Get file for editing. A lock is placed on the s.file.
.tp
.B -F
Don't verify the file checksum.
.tp
.AN \-G name
Place the checked out file in 
.I name 
instead of the default.
.tp
.B \-g
Suppress the retrieval of any text.
.tp
.B -H
Put file in its historic location.
.tp
.B -h
Invert sense of file's hash flag.
.tp
.AN \-i list
Include revs in 
.IR list .
.tp
.B \-k
Don't expand RCS or SCCS keywords. \-k is implied by \-e.
.tp
.B -l
Same as -e.
.tp
.AN \-M rev
Merge with 
.IR rev .
.tp
.B \-m
Prefix each line with the revision of last modification.
.tp
.B \-N
Prefix each line with its line number.
.tp
.B \-n
Prefix each line with the filename.
.tp
.B -P
Write to stdout, force get.
.tp
.B \-p
Write file to standard output (useful in scripts).
Required with \-r
.I rev 
where 
.I rev 
is anything other than the most recent delta.
.tp
.B \-q
Run quietly.
.tp
.B -R
Rev is part of pathname.
.tp
.AN \-r rev
Get this revision.
.tp
.B \-S
If a gfile exists, don't check it out again.
.tp
.B -s
Same as -q.
.tp
.B \-T
Set the gfile's modification time to the delta's
creation time.
.tp
.B -t
Ignored, SCCS compat.
.tp
.B \-u
Prefix each line with the user who last modified it.
.tp
.AN \-x list
Exclude revs in 
.IR list .
.SH "SEE ALSO"
.SA co 1
.br
.SA edit 1
.br
.SA exclude 1
.br
.SA include 1
.SH CATEGORY
.B File
