.so ../bk-macros
.TH "bk gethost" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk gethost \- display machine name
.SH SYNOPSIS
.B bk gethost [-r]
.SH DESCRIPTION
.LP
Outputs the fully-qualified name of the machine.
Used primarily when doing
.B bk
scripting.
.OPTIONS
.TP 4
.B \-r
print the real host name, ignoring \f(CB$BK_HOST\fP.
.SH SEE ALSO
.SA getuser
.SH CATEGORY
.B Utility
