.so bk-macros
.TH "bk intro-general" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk General-intro \- definitions of \*(BK terms and HOWTO guides
.SH DESCRIPTION
.LP
\*(BK is a distributed revision control system.  It is similar to
RCS and SCCS (it uses an SCCS-compatible file format) with added features
for configuration management and distributed revision control.  Both
SCCS and RCS compatible command line interfaces are provided.
.LP
If you are using \*(BK on Windows 2000/NT/98, please note that
\*(BK's interface is identical to the interface on Unix. This means that
you need to be in a shell to issue a \*(BK command. To get into a
shell, click on the 
.B Start->BitKeeper->bash shell
menu entry.
You can customize the shell window by right-clicking on the title bar and
selecting the 
.B Properties
menu.
.LP
There are graphical interfaces for browsing, merging, and checking in
files.  Try 
.B bk helptool gui
for more information.
.LP
General usage is designed to be as similar to SCCS as possible for
typical users.  A user does not need to use the distributed features or
configuration management features when doing basic revision control.
.LP
For specific help, try
.B bk helptool
or 
.B bk help
to get a list of topics.
For new users, may we suggest the following topics in order:
.LP
.SA setup 1
.SA Basics-intro 1
.SA gui 1
.\" help://General/Overview
.SH CATEGORY
.B General
