.so bk-macros
.TH "bk HOWTO" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== BitKeeper quickstart ===================
.SH NAME
bk HOWTO \- \*(BK HOWTO guides
.SH DESCRIPTION
.LP
Quickstart guides are recipes for accomplishing common tasks with
\*(BK.  The guides contain little or no explanations.  Each command
has detailed help which you can see by running
.B bk help
.ARG command .
.LP
Project leads should read the
.B bk help HOWTO-setup 
and
.B bk help HOWTO-bkd
sections.  Developers
who just want to use an existing package only 
need to read
.B bk help
.BR HOWTO-developer .
.SH "SEE ALSO"
.SA HOWTO-bkd 1
.SA HOWTO-developer 1
.SA HOWTO-setup 1
.\" help://General/Quickstart
.\" help://quickstart
.SH CATEGORY
.B General
