.so ../bk-macros
.TH "HOWTO-developer" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    =================== Quickstart Developer =======================
.SH NAME
bk Howto-developer \- howto: working with \*(BK repositories
.SH DESCRIPTION
.LP
Here is an example sequence of commands used to create a new package,
import files into the package, create a clone of the package for
modifications, do some work in the clone, pull new work from the
master tree down, merge, and then push the work back up.
.sp
.DS
# Create a clone on your development machine.  
# The destination directory should not exist.
bk clone bk://host.domain:6666/project ~/myproject

# Do some work.
cd ~/myproject
bk vi index.cgi

# Check it in and create a changeset.
bk citool

# Pull any new work down from the work tree.  
# This example assumes that someone else also changed
# "index.cgi" and their changes overlapped the local changes.
# The pull command will say that there are 
# overlapping changes and will not apply the new work.
bk pull

# Resolve the conflicts.  This step is only necessary if pull
# said there were conflicts which could not be automerged.
bk resolve

# push the merge and the local changes back up.
bk push
.DE
.SH "SEE ALSO"
.SA Howto
.SH CATEGORY
.B Overview
.\" help://qs_developer
.\" help://qs_dev
