.so bk-macros
.TH "bk HOWTO" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== BitKeeper quickstart ===================
.SH NAME
bk Howto \- \*(BK HOWTO guides
.SH DESCRIPTION
.LP
Howto guides are recipes for accomplishing common tasks with
\*(BK.  The guides contain little or no explanations.  Each command
has detailed help which you can see by running
.B bk help
.ARG command .
.LP
Project leads should read the
.B bk help Howto-setup 
and
.B bk help Howto-bkd
sections.  Developers
who just want to use an existing package only 
need to read
.br
.B bk help
.BR Howto-developer .
.SH "SEE ALSO"
.SA Howto-bkd 1
.SA Howto-developer 1
.SA Howto-setup 1
.\" help://General/Quickstart
.\" help://quickstart
.SH CATEGORY
.B Overview
