.so bk-macros
.TH "bk histtool" 1 20%E% "\*(BC" "\*(UM"
.\"    =============== BitKeeper Graphical History Browser ===============
.SH NAME
bk histtool \- \*(BK graphical history browser
.SH SYNOPSIS
.Bc bk histtool [
.ARGc filename
.B ]
.SH DESCRIPTION
.LP
The histtool command is used to graphically browse file history.
It may be used on any file under revision control, including the
ChangeSet file. When no filename is given, the entire package history
is shown.
.LP
When the tool starts, there are two windows, the top window
which is used to display the graph of revision history and the bottom
window which is used to show history or differences between versions.
.SH "HISTORY AND DIFFERENCES"
.LP
When the histtool starts up, the entire revision history of the file
is in the text window.
.LP
To view the history for just one revision, left click once on that
revision in the graph.
.LP
To see differences between two revisions, left click once on the older
revision and right click once on the newer revision.  The differences
will be displayed in the text window.  You can right click on another
revision and diff again.  The default diff format is
.B \-u
(unified diffs).
.LP
Once the annotated file listing is shown, you can then click on
the lines to view the checkin comments that are associated with the
revision that the line represents. Double clicking on an annotated
line brings up csettool and shows all of the other files that were
modified in the same changeset as the selected line.
.LP
To get a side\-by\-side view of the differences, select the two revisions
and click on the "Diff tool" button.
.LP
To see the entire file for a given revision, double click the left
mouse button on the revision.  The text shown for the file is
annotated with the user name and revision level for each line. This
text is generated with the 
.B bk get \-ump
command.
.SH CHANGESETS
.LP
When operating on the ChangeSet file, the behavior is slightly
different.  Double\-clicking a revision displays the revision history
of the changeset and the history of the changes to each file contained
in that changeset.
.LP
If you click left/right on a range of changesets, you will get the
history of the entire range of changesets.  To see the history and
the differences in detail, you can click on the "View changeset"
button and that will pop up a changeset browser.  Typical usage is to
browse the ChangeSet file with histtool and drill down using
.B bk
.BR csettool .
.SH BINDINGS
.LP
The scrollbars can be used to orient the view of either window. 
In addition, there are the following keyboard bindings:
.TP 18
.B LeftArrow
Scroll graph window left 1 line.
.tp
.B RightArrow
Scroll graph window right 1 line.
.tp
.B Shift\-LeftArrow
Scroll graph window left 1 screen.
.tp
.B Shift\-RightArrow
Scroll graph window right 1 screen.
.tp
.B Shift\-UpArrow
Scroll graph window up 1 line.
.tp
.B Shift\-DownArrow
Scroll graph window down 1 line
.tp
.B Shift\-PageUp
Scroll graph window up 1 screen.
.tp
.B Shift\-PageDown
Scroll graph window down 1 screen.
.tp
.B Shift\-Home
Scroll graph window to the first revision.
.tp
.B Shift\-End
Scroll graph window to the last revision.
.TP
.B UpArrow
Scroll text window up 1 line (also Control\-y).
.tp
.B DownArrow
Scroll text window down 1 line (also Control\-e).
.tp
.B PageUp
Scroll text window up 1 screen (also Control\-b).
.tp
.B PageDown
Scroll text window down 1 screen (also Control\-f).
.tp
.B Home
Scroll text window to the top.
.tp
.B End
Scroll text window to the bottom.
.TP
.B s
Show the raw SCCS file.
.tp
.B d
Show the differences between the selected item and its parent. If
a graph node is selected, the difference between it and its parent
are shown. However, if a line within the annotated file listing is
selected, the difference between the selected revision and its parent
are shown.
.tp
.B h
Show the entire revision history comments.
.tp 
.B /
Search the text window for a string.
.tp
.B ?
Reverse search.
.tp
.B n
Search for the next occurrence of the string.
.tp
.B Control\-q
Quit histtool.
.SH "SEE ALSO"
.SA Intro-GUItools 1
.SH CATEGORY
.B GUI-tools
.br
.B Common
.br
.B File
.br
.B Repository
.\" help://bk-sccstool.1
.\" help://bk-sccstool
.\" help://sccstool
