.so bk-macros
.TH "bk history" 1 20%E% "\*(BC" "\*(UM"
.\"    ================= Viewing changeset and file history =================
.SH NAME
bk history \- guide to viewing changes over time of files and repositories
.SH DESCRIPTION
.LP
Note: there is a GUI tool for viewing changes, see
.BR "bk revtool" .
.LP
If you want to view the high\-level changes to a package, (i.e. the changes
associated with the ChangeSet) type:
.DS
$ bk changes
.DE
Two ways to view file history are on a per\-file basis and a method
which shows the changes over a set of files.  A third method is to
use "bk revtool" which is a graphical file viewer.
.LP
The revision history of a file can be accessed by typing:
.DS
$ bk prs foo.c
.DE
Prs has many options. The most useful is probably the \-r option that
lets you specify a revision.
.LP
To see the most recent check\-in for every file in the current directory:
.DS
$ bk prs \-r+
.DE
To see all changes from Alpha to Beta, (assuming you tagged the files
with those tags) try:
.DS
$ bk prs \-cAlpha..Beta
.DE
The 
.B bk sccslog
command is useful when you are interested in the history
of the entire tree or subdirectory, not just the per\-file revision history.
The 
.B bk sccslog 
command sorts all the changes based on date, so you see deltas 
from different files in chronological order.  This process can take 
substantial CPU and memory resources, but the following is a very useful 
thing to see:
.DS
$ bk sfiles | bk sccslog - | more
.DE
.B bk sccslog 
supports the same range notation as prs.
.SH "SEE ALSO"
.SA changes 1
.SA prs 1
.SA range 1
.SA sccslog 1
.SH CATEGORY
.B Overview
.br
.B Repository
