.so ../bk-macros
.TH "bk id" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk id \- display the identity of a package or repository
.\" help://identity
.SH SYNOPSIS
.B bk id
.B [\-5rS]
.SH DESCRIPTION
In \*[BK], each repository has two identities: a package
identity and a repository identity.
.LP
The package identity is the same across all repository instances
of the same package.  Two repositories may synchronize with each
other if and only if they have the same package identity.  
.B bk id
displays the package identity.
.LP
The repository identity is different in each repository,
regardless of the package.
.Q bk id \-r
displays the repository identity.
.SH OPTIONS
.TP \-r
.B \-5
Return package identity as an md5key
.tp
.B \-r
displays the repository identity
.tp
.B \-S
in a nested collection return the identity of the current repo, rather
than the product.
.SH "SEE ALSO"
.SA newroot
.SA terms
.SH CATEGORY
.B Repository
.br
.B Admin
