.so ../bk-macros
.TH "bk identity" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk identity \- display the identity of a repository
.SH SYNOPSIS
.B bk identity
.OPT \-r
.SH DESCRIPTION
.LP
.B identity
is command used to display the
.I identity
of a repository.  The
.I identity
is a unique identification of related repositories that can
exhange csets using
.B push
and
.BR pull .
With the 
.B \-r
option the 
.I repo_id
is returned.  The repo_id is a unique identification of this copy of
the repository.
.SH "SEE ALSO"
.SA newroot 1
.SA terms 1
.SH CATEGORY
.B Repository
.br
.B Admin
