.so bk-macros
.TH "bk import" 1 20%E% "\*(BC" "\*(UM"
.\"    ================= Importing files into BitKeeper =================
.SH NAME
bk import \- import a set of files into a \*(BK package
.SH SYNOPSIS
.Bc bk import [-AefHiqrvu] [
.OPTreq \-c tag
.Bc ] [
.OPTreq \-j n
.Bc ] [
.OPTreq \-l file
.Bc ] [
.OPTreq \-S sym
.Bc ] [
.OPTreq \-t type
.B ]
.ARG dir|patch
.ARG destination
.SH DESCRIPTION
.LP
Use bk import to put non-\*(BK files into a \*(BK package and check-in
the initial revision.
.LP
The destination should be a bitkeeper package.  Please see
bk help setup if a package is not yet set up.
.LP
You can import files by specifying the directory
containing files for import (Note: All files under the directory will
be imported.  If a subset is desired, specify using a list or run 
interactively.)
.DS
bk import /path/to/src_files /path/to/package
.DE
.LP
You may also specify files to import using an external list.  The
path names of files in the list must be relative to the source directory.
.DS
bk import -l/tmp/list ~/src/files ~/package
.DE
bk import can be run interactively to include and exclude files using
regular expressions.
.DS
bk import -i ~/src_files ~/package
End patterns with "." by itself or EOF
Include>> *.c
Include>> *.h
Include>> Makefile
Include>> .
.DE
Importing from a CVS tree:
.DS
$ bk import -v -tCVS warehouse new
.DE
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-A
Attic processing (CVS import only).  Moves all files which do not have
name conflicts from the Attic subdirectories to the enclosing repository,
i.e., "mv Attic/*,v .".
.tp
.OPTreq \-c tag
do not import anything after
.ARG tag .
(RCS/CVS only)
.tp
.B \-f
Force; do not prompt for list editing.
.tp
.B \-H 
do not pass \-h option to rcs2sccs (turns off verification, faster, unsafe).
.tp
.B \-i
Like \-x but includes only files which match.
.tp
.OPTreq \-j n
n-way parallel for RCS conversion.
.tp
.OPTreq \-l file
Use the list of files in 
.ARG file .
.tp
.B \-q
Be quiet.
.tp
.B \-r
Do not do rename processing when doing patch imports.
.tp
.OPTreq \-S sym
Add tag 
.ARG sym
to the changeset created around the import
.tp
.OPTreq \-t type
Specify import file type.  
.ARG type
can be one of:
.if t .RS .5i
.if n .RS .3i
.tp
.B plain
Import plain text files
.tp
.B patch
Import a patch (diffs)
.tp
.B RCS
Import RCS files
.tp
.B CVS
Import CVS files
.tp
.B SCCS
Import SCCS files
.RE
.tp
.B \-u
Run files through bk undos first; this will convert
DOS style end of lines to Unix style end of lines.
Used with -tCVS or -tRCS.
.tp
.B \-v
Be verbose.
.tp
.B \-x
Prompts for a regular expression to apply to the list
of files.  All matches are excluded.
.SH "SEE ALSO"
.SA rcs2sccs 1
.SA undos 1
.SH CATEGORY
.B Repository
