.so bk-macros
.TH "bk import" 1 20%E% "\*(BC" "\*(UM"
.\"    ================= Importing files into BitKeeper =================
.SH NAME
bk import \- import a set of files into a \*(BK package
.SH SYNOPSIS
.B bk import -tpatch [OPTIONS] 
.ARG patch
.ARG destination
.br
.B bk import -tplain [OPTIONS]
.ARG directory
.ARG destination
.br
.B bk import -tRCS\ \  [OPTIONS]
.ARG directory
.ARG destination
.br
.B bk import -tCVS\ \  [OPTIONS]
.ARG directory
.ARG destination
.br
.B bk import -tSCCS\  [OPTIONS]
.ARG directory
.ARG destination
.SH DESCRIPTION
.LP
Use bk import to put plain text files, patches (diff -Nur), SCCS files, and 
RCS and CVS files (in this document RCS will mean both RCS AND CVS)
into a \*(BK package.  bk import does its work outside of your original tree
thus leaving the original files intact while importing them into a 
\*(BK package.
.LP
In the case of RCS and SCCS files,
import should only be invoked once into a destination package.
It can be used repeatedly if you are importing 
traditional patches (diff -Nur) into a repository over time.  
.LP
A more detailed explanation of importing the different types of files
can be found below.
.\"You can import files by specifying the directory
.\"containing files for import (Note: All files under the directory will
.\"be imported.  If a subset is desired, specify using a list or run 
.\"interactively.)
.\".DS
.\"bk import /path/to/src_files /path/to/package
.\".DE
.\".LP
.\"You may also specify files to import using an external list.  The
.\"path names of files in the list must be relative to the source directory.
.\".DS
.\"bk import -l/tmp/list ~/src/files ~/package
.\".DE
.\"bk import can be run interactively to include and exclude files using
.\"regular expressions.
.\".DS
.\"bk import -i ~/src_files ~/package
.\"End patterns with "." by itself or EOF
.\"Include>> *.c
.\"Include>> *.h
.\"Include>> Makefile
.\"Include>> .
.\".DE
.\"To import from a CVS tree:
.\".DS
.\"bk import -v -tCVS warehouse new
.\".DE
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-C
Do not commit the ChangeSet.
.tp
.B \-f
Force; do not prompt for list editing.
.tp
.B \-F
Fast; run more quickly for large imports.
.B NOTICE:
use this option 
.B only
when you know that this is the only \*(BK activity you are doing. 
Using this option on two parallel imports may cause \*(BK consistency
problems.
.tp
.B \-H 
do not pass \-h option to rcs2sccs (turns off verification, faster, unsafe).
.tp
.B \-i
Prompts for a regular expression to apply to the list of files.
All matches are included. (For use with all types except patches.)
.tp
.OPTreq \-l file
Use the list of files in 
.ARG file .
(For use with all types except patches.)
.tp
.B \-q
Be quiet.
.tp
.OPTreq \-S sym
Add tag 
.ARG sym
to the changeset created around the import
.tp
.OPTreq \-t type
Specify import file type.  
.ARG type
can be one of:
.if t .RS .5i
.if n .RS .3i
.tp
.B plain
Import plain text files
.tp
.B patch
Import a patch (diffs)
.tp
.B RCS
Import RCS files
.tp
.B CVS
Import CVS files
.tp
.B SCCS
Import SCCS files
.RE
.tp
.B \-v
Be verbose.
.tp
.B \-x
Prompts for a regular expression to apply to the list
of files.  All matches are excluded.  (For use with all types except patches.)
.SH "RCS OPTIONS"
.if t .TP
.if n .TP .8i
.B \-A
Attic processing (CVS import only).  Moves all files which do not have
name conflicts from the Attic subdirectories to the enclosing repository,
i.e., "mv Attic/*,v .".
.tp
.OPTreq \-c tag
do not import anything after
.ARG tag .
.tp
.OPTreq \-j n
n-way parallel for RCS conversion.
.tp
.B \-u
Run files through bk undos first; this will convert
DOS style end of lines to Unix style end of lines.
.SH "PATCH OPTIONS"
.if t .TP
.if n .TP .4i
.tp
.B \-r
Do not do rename processing when doing patch imports.
.tp
.B \-R
If a patch fails to apply cleanly, back out the entire operation
and exit with a failure.
.tp
.OPTreq \-y comment
Set the message for the delta comments for all files to
.B <comment>
rather than "Import patch PATCHNAME".
.SH "IMPORTING PATCHES"
.LP
\*(BK can be used to track external work by importing patches (diff -Nur)
into a \*(BK package.  \*(BK can help with downsides of patches, namely that
renames are not tracked well and that there generally aren't very good comments 
if any at all attached to the changes being made.
.\" XXX - I don't know
.\" if the above is a completely true and pertinent statement.
A rename in a patch is viewed as the deletion of one file and the
creation of another file, so to track these, bk import will launch 
bk renametool which is the graphical tool used to manually 
match the deleted files with the newly created files.
.SH "IMPORTING RCS FILES"
.LP
The default branch of the RCS tree is the one that will be imported.
All other branches are discarded. 
.\" which is okay because
.\" XXX - Ask lm why.  I'm not sure why this is okay.
Metadata from the ,v files is preserved upon import.  Thus saving
the history of your files.
.LP
This is a one time only import.  Importing to a clone of the destination 
package is advised in case the import fails, the package won't get
corrupted.  
.LP
The type of import requires RCS 5.6 or later.
.SH "IMPORTING PLAIN TEXT"
.LP
Importing a plain text file into a \*(BK package can only be done once.
If there is already a file in the package that has the same name as a
file to be imported the import will fail.  
.LP
If a package is already
populated with files use the -i, -x or -l options 
to avoid trying to import files already in the package.  Because of the
preceeding constraints, import does not catch renames with plain text files.
If a file has been renamed, it can be imported, but the original file will
still exist in the package so it is necessary to remove the original file
from the package tree after the import of the renamed file.
.LP
Plain text files can be imported from a directory, 
.DS
bk import /path/to/src_files ~/package
.DE
from a list of files relative to the source directory, 
.DS
bk import -l/tmp/list /path/to/src_files ~/package
.DE
or by using regular expressions in interactive mode
.DS
bk import -ix ~/src_files ~/package
End patterns with . by itself or EOF
File name pattern to include>> *.c
File name pattern to include>> *.h
File name pattern to include>> Makefile
File name pattern to include>> .
End patterns with . by itself or EOF
File name pattern to exclude>> *.o
File name pattern to exclude>> .
.DE
.SH "IMPORTING SCCS FILES"
.LP
Teamware and other SCCS files can be imported.  The history of the file is
preserved, but the unmerged branches are discarded.  This is okay because 
the necessary metadata is in the mainline.  
.LP
Importing \*(BK files is not supported; use bk clone.
.SH "ERROR HANDLING"
.LP
Import does not handle errors in a robust way.  If unsuccessful, import
may leave work half done in the destination package.  It is suggested that
the import destination repository is a clone of the original package in case of
a failed import.
.SH "SEE ALSO"
.SA rcs2sccs 1
.SA undos 1
.SH CATEGORY
.B Repository
