.so ../macros
.TH "bk info" 1 08/18/00 "\*(BC" "\*(UM"
.\"    =========== Information about files in BitKeeper ===========
.SH NAME
bk info \- show the state of a BitKeeper file or set of files
.SH SYNOPSIS
.B bk info [
.IB file\ list ]
.SH DESCRIPTION
.LP
The info command shows the state of a set of specified or implied files.
.LP
The state is as follows:
.if t .AX
.if n \{\
.sp
.nf
.\}
slib.c:     1.361 1.362 lm 99/09/22 03:36:18 (modified, needs delta)
sinfo.c:    1.16 1.17 lm 99/09/22 22:15:58 (modified, needs delta)
fdiff.c:    1.77 1.78 lm 99/09/22 22:15:57
.if t .XA
.if n \{\
.fi
.\}
.LP
The field names are:
.if t .TP 1i
.if n .TP 1.75i
file name
Name of file.
.tp
Parent revision
Basis for the edited file.
.tp
new revision
What it would be called if you checked it in.
.tp 
user name 
User name of the user who edited the file.
.tp
date and time 
Time when the file was locked.
.tp
(state) 
If present, indicates that the file is modified.
.SH NOTE
.LP
The info command is an alias for the program sinfo. The "info" command
name was already taken by the GNU document browser.
.\" help://File/sinfo
.SH CATEGORY
.B File
