.so ../bk-macros
.TH "bk isascii" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk isascii \- check that a file is ascii
.SH SYNOPSIS
.B bk isascii
.ARG filename
.SH DESCRIPTION
.B bk isascii
looks through a file for binary data which \*(BK can not handle without
encoding the file.  This consists of a NULL (zero byte).
.SH EXIT STATUS
.B bk isascii
returns exit status:
.TP
0
if
.ARG filename
is ASCII
.tp
1
if
.ARG filename
is not ASCII
.tp
2
if an error occurs
.SH CATEGORY
.B Utility
