.so ../bk-macros
.TH "bk ignore" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk ignore \- ignore shell glob patterns
.SH SYNOPSIS
.Bc bk ignore [
.ARG 'glob' 
.Bc [
.ARGc 'glob'
.Ic .\|.\|.
.B ]]
.SH DESCRIPTION
.LP
The 
.B ignore
command is used to tell \*(BK about files which should
be ignored when looking for extras files not under revision control.
It affects the output of 
.B bk sfiles \-x
and all commands which use that output, such as 
.B bk status
and 
.B bk
.BR extras .
.LP
Typical things to ignore are object files, core files, a.out, *.exe, etc.
.LP
The patterns are matched against both the basename of the file and the
pathname of the file.  If you are trying to never have the file 
.ARG JUNK
match, regardless of which directory it is in, you can say
.DS
bk ignore 'JUNK'
.DE
.ft R
and that will match 
.ARG JUNK
and
.ARG sub/dir/JUNK
but not
.ARG JUNK-PRECIOUS .
.LP
If you want to match a file in just one subdirectory, you can do
.DS
bk ignore sub/directory/this_one
.DE
which will match 
.ARG sub/directory/this_one
but not
.ARG other_dir/this_one .
.LP
If you give ignore no arguments it will print out the current ignore list.
.LP
The ignore list is saved in the file
.I BitKeeper/etc/ignore.
You may edit this file if you wish; the format is simply one glob per line.
Editing the ignore file is the only way to remove entries from the list.
.LP
There is currently no default list, but the following is suggested:
.DS
core
*.o
*.swp
*.a
*.exe
*~
*.rej
*.orig
BitKeeper/etc/*
BitKeeper/tmp/*
BitKeeper/triggers/*
.DE
.SH BUGS
.LP
There is no per directory
.I \.bkignore
list, nor is there a
.I ~/ \.bkignore list.
.SH SEE ALSO
.LP
.SA sfiles 1
.SA extras 1
.SH CATEGORY
.B Admin
