.so ../bk-macros
.TH "bk key2rev" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk key2rev \- convert \*(BK keys to revisions
.SH SYNOPSIS
.B cat keys | bk key2rev
.ARG file
.SH DESCRIPTION
This utility takes one or more keys on the standard input and
prints the corresponding revision in 
.ARG file
implied by the key.
.SH CATEGORY
.B Utility
