.so ../bk-macros
.TH "bk bin" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk links \- make links to the bitkeeper binary installation directory
.SH SYNOPSIS
.\"
.B bk links
.ARG bk_bin_dir
.OPT public_dir
.SH DESCRIPTION
.LP
Makes links from the specified public directory to the BitKeeper 
binary installation directory.  Makes links to /usr/bin if no
public directory is specified.
.SH SEE ALSO
.SA bin
.SH CATEGORY
.B Utility
