.so ../bk-macros
.TH "bk latest" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk latest \- run command using the latest version of bk
.SH SYNOPSIS
.B bk latest
.ARG command
.SH DESCRIPTION
Run the specified
.ARG command
using the latest released version of BitKeeper. The new BitKeeper
version is downloaded from http://bitkeeper.com and installed in
$HOME/.bk/latest.
.SH CATEGORY
.B Utility
