.so ../bk-macros
.TH "bk makepatch" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk makepatch \- creates \*(BK patches
.SH SYNOPSIS
.B bk makepatch
.[B] \-vd
.[OPTreq] \-r range
.[B] \-
.SH DESCRIPTION
.LP
The makepatch command is a low level command used to generate \*(BK patches.
.SH OPTIONS
.TP \-r\*<range\*>
.B \-B
Include the data from any BAM files in the patch. Normally BAM files
are sent without the implied data.
.tp
.B \-C
Generate a patch compatible with any supported versions of \*(BK.
.tp
.B \-d
Add a header with the unified diffs to the top of the \*(BK patch.
.tp
.OPTreq \-r range
Generate a \*(BK patch of the changesets in
.ARG range .
.tp
.B \-v
Be more verbose for each instance.
.tp
.B \-
Instead of specifying the range with
.QR \-r ,
this form expects the revisions on the standard input, one per line,
either as keys or revisions.
.SH NOTES
In general, users do not use this command directly, it is called by
.B bk pull
or
.BR "bk push" .
If patches are to be sent to a non-\*(BK user then use
.BR "bk export" .
.LP
By default patches are created in the latest patch format known by
this version of \*(BK. With
.B \-C
patches will be compatible with oldest version of \*(BK that is still
supported.
.SH SEE ALSO
.SA export
.SA takepatch
.SH CATEGORY
.B Repository
