.so bk-macros
.TH "bk mv" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk mv \- move file[s]
.SH SYNOPSIS
.B bk mv
.ARG "source file[s]"
.ARG "destination file or directory"
.SH DESCRIPTION
.LP
To move a file from
.ARG A
to
.ARG B
do this:
.DS
$ bk mv A B
.DE
.ft R
The
.B mv
command will move the checked out file (if any) as well as the
revision control file.  Edited files are also moved and then redited,
preserving any changes made but not yet checked in.
The rename
will appear as an additional change to the file when you commit the
next changeset.
.LP
Renames propogate just like content changes,
i.e., they happen automatically when you pull changes into your 
repository from another repository unless you have also moved the file.
In that case, the resolver will prompt you to choose a name.
.SH NOTES
.LP
.B bk mv
will not move directories, please use
.B bk mvdir
for that. 
.SH SEE ALSO
.SA commit 1
.SA mvdir 1
.SA pull 1
.SA push 1
.SA resync 1
.SA rm 1
.SA rmdir
.SH AVAILABILITY
.BU
Fully supported in \*(BK Professional in all repositories.
.BU
Limited functionality in \*(BK Basic.
bk mv should only be used in the master repository 
since the resolver can not merge rename conflicts in \*(BK Basic.
The actual requirement is that it is only
used in one repository, then all repositories must sync with
that repository.  The easiest way to accomplish this is to
establish policy which says that bk mv may only be used in the
master repository.
.SH CATEGORY
.B Basics
