.so ../bk-macros
.TH "bk newroot" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk newroot \- change the identity of a repository
.SH SYNOPSIS
.B bk newroot
.[OPTreq] \-k randombits
.[OPTreq] \-y comment
.br
.B bk newroot
.SH DESCRIPTION
.LP
.B bk newroot
is an administrative command used to generate a new 
.I identity
for a repository.  It is typically used only after having repaired a
repository.  After running
.B bk newroot
that repository will not be able to push to or pull from it's parent or
any other related repository.
.SH OPTIONS
.TP \-K\*<bits\*>
.OPTreq \-k bits
Specify the string of random bits used as part of the repository identity.
The string must be 16 hex digits.
.TP \-y\*<comment\*>
.OPTreq \-y comment
Specify a comment to be used for why the rootkey was changed.
Must be a single line.
.SH "SEE ALSO"
.SA id
.SA clone
.SA pull
.SA push
.SA terms
.SH CATEGORY
.B Admin
