.so ../bk-macros
.TH "bk newroot" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk newroot \- change the identity of a repository
.SH SYNOPSIS
.B bk newroot
.[OPTreq] \-k randombits
.SH DESCRIPTION
.LP
.B newroot
is an administrative command used to generate a new 
.I identity
for a repository.  It is typically used only after having repaired a
repository.  After running
.B newroot
that repository will not be able to push to or pull from it's parent or
any other related repository.
.SH OPTIONS
.if t .TP 8
.if n .TP 12
.[OPTreq] \-k bits
Specify the string of random bits used as part of the repository identity.
The string must be 16 hex digits.
.SH "SEE ALSO"
.SA identity
.SA clone
.SA pull
.SA push
.SA terms
.SH CATEGORY
.B Admin
