.so bk-macros
.TH "bk new" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk new \- add a file to the repository
.SH SYNOPSIS
.B bk new [-q]
.ARG file
.br
.B bk sfiles \-x | bk new 
.I -
.SH DESCRIPTION
.LP
The 
.B new
command is used when placing files under \*(BK control.
The first form checks in a single file, the second form checks in
all files in the repository which are not under \*(BK control
(be careful, the second form will check in anything, such as
.IR  a.out ,
.IR *.o ,
.IR core ,
etc.).
.LP
When checking in multiple files in a directory, do:
.DS
bk sfiles -x *.[ch] | bk new - 
.DE
When you want to check in files in the current directory and all 
subdirectories, do the following:
.DS
bk sfiles -x | egrep '*.[ch]$' | bk new -
.DE
After the files are checked in, don't be surprised to see that
the files are no longer in your directory. The process of checking
in files removes the files from the directory and places them in
the SCCS directories.  Once in the SCCS directory, the file can be
retrieved with the 
.B bk get
or 
.B bk edit
commands.  Most versions of the
Unix make command know about SCCS and will automatically check out
files as they are needed.
.SH OPTIONS
.TP
.B \-q
be quiet.
.SH SEE ALSO
.SA edit 1
.SA get 1
.SA sfiles 1
.SH CATEGORY
.B File
.br
.B Common
