.so ../bk-macros
.TH "bk pending" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk pending \- list deltas which need to be in a changeset
.SH SYNOPSIS
.B bk pending
.SH DESCRIPTION
.LP
The
.B bk pending
command shows changes that have been checked into your local work
area, but not yet committed to a changeset.
You have to commit to a changeset in order to send the change to
other work areas.
.LP
To see what needs to be committed to a change set, run:
.DS
$ bk pending
.DE
.SH NOTE
This command is roughly the same as
.DS
$ bk -R sfiles -pA | bk -R prs -
.DE
.SH EXIT STATUS
.LP
.B bk pending
returns exit status:
.TP
0
on success.
.tp
1
on failure.
.SH "SEE ALSO"
.SA commit
.SA changes
.SA prs
.SA sfiles
.SH CATEGORY
.B Repository
