.so ../bk-macros
.TH "bk parent" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk parent \- show or set the parent repository
.SH SYNOPSIS
.Bc bk parent [
.Bc -lqpr] [
.ARGc repository
.B ]
.SH DESCRIPTION
.LP
The parent command prints or sets the default location where the 
\fBbk pull\fR/\fBbk push\fR commands get/put new work.
.LP
With no argument, the command prints the parent name.  With an argument, it sets
the parent to that argument.  
.LP
The parent is automatically set when a repository is cloned and will be
named according to the access method (see bk help url for more information).
.SH OPTIONS
.TP
.B \-l
Literal; i.e. disable the auto-subsitution of "localhost" with the
real host name when we store the parent pointer. This also disable
the auto-subsitution of relative path to absolute path.
This is used by advance user for setting up ssh port forwarding
from a localhost port. It is probably a "bad" idea to use this option
on a repository shared over a network file system such as NFS or SAMBA.
"localhost" may point to different parent repositories on different
host.
.tp
.B \-q
Run quietly.
.tp
.B \-p
Just print parent without other text. (for scripts)
.tp
.B \-r
Remove the parent pointer.
.SH "SEE ALSO"
.SA bkd 1
.SA clone 1
.SA pull 1
.SA push 1
.SA resync 1
.SA url 1
.SH CATEGORY
.B Repository
