.so ../bk-macros
.TH "bk pull" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    ============== Pulling changes into your repository ==============
.SH NAME
bk pull \- update a repository from its parent[s]
.SH SYNOPSIS
.B bk pull
.[B] \-iqRsTu
.[OPTreq] \-r rev
.[OPTequal] \-E env var
.[OPTreq] \-c n
.[ARG] parent \ .\|.\|.
.SH DESCRIPTION
.LP
.B bk pull
updates a repository from its incoming parent[s].
Changes are retrieved and automatically applied, if possible.
You will only be asked to resolve conflicts by hand if a file
has overlapping changes (changes where both repositories have
touched the same line in the same file).
.LP
To see what would be pulled run
.DS
bk changes -aR
.DE
.\" XXX - do I really want to tell them this?
.ig
.LP
.B bk pull
will refuse bring in changes to files which are modified in the
local repository.
Should this occur, one way around it is to do
.DS
bk -cr diffs -up > DIFFS
bk -r unedit
bk pull
bk patch -p1 -g1 < DIFFS
.DE
If that works, you are done.  If that does not work then the best thing
is to unedit the attempted patch, unpull the changes, redo the patch
(which will now work), commit those changes and redo the pull.
..
.LP
.B bk pull
normally runs resolve, the tool which applies the pulled changes,
automatically.  Resolve will look at each change, make sure there are
no conflicts that it can't merge, and apply the change.  You may have to
(or want to) run resolve manually.  If you do not want automatic merges,
i.e., you want to diff them by hand, then use the
.Q \-i
option.  If resolve
was run automatically and it found conflicts, the changes have 
.B not
been applied;
you will need to run an interactive resolve to merge and apply the changes.
.LP
You can override the default parent by specifying a different one.
Doing so changes the parent for the duration of this command only.
.LP
If you've pulled in error you may use
.B bk unpull
to remove the changesets introduced by the pull.
Please read the 
.B bk unpull
man page for important information about what is and is not unpulled.
.SH OPTIONS
.TP \-E\*<env\*>=\*<val\*>
.OPTreq \-c n
try to get the remote lock
.ARG n
times before giving up (default forever).
.tp
.OPTequal \-E env val
Export environment variable to remote site.
The environment variable must start with
.V BKU_ .
.tp
.B \-i
Turn off automerge feature in resolve.
For each file with parallel work, you are prompted
to examine the changes and either manually or automatically
merge them.
.tp
.B \-q
Be quiet.
.tp
.B \-R
Do not run resolve at all.  You must run 
.B bk resolve 
later.
.tp
.OPTreq \-r rev
Pull up to and including this revision, but exclude later changes.
(Or key or changeset revision. See 
.B bk help terms
under 'rev argument')
.tp
.B \-s
Pass 
.Q \-s
to resolve (\c
.Q \-s
means do not do interactive resolve of any conflicts, leave that for later.)
.tp
.B \-T
Pass 
.Q \-T
to resolve (\c
.Q \-T
means do not use the GUI tools.)
.tp
.B \-u
Do not complete the pull if there are local changesets, i.e., insist
that this operation is an update operation.
.SH "SEE ALSO"
.SA bkd
.SA parent
.SA push
.SA changes
.SA resolve
.SA triggers
.SA unpull
.SH CATEGORY
.B Common
.br
.B Repository
