.so ../bk-macros
.TH "bk populate" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk populate \- fill in components in a sparse product repository
.SH SYNOPSIS
.B bk populate
.[B] \-lqr
.[OPTreq] \-M module \ ...
.[ARG] from \ .\|.\|.
.SH DESCRIPTION
.LP
The populate command is used to add modules to a sparse product,
or to reclone all components implied by the cached modules list.
.LP
When cloning a product, it is possible to clone a subset of it by 
specifying one or more modules.
If later you want to add another module, the populate command 
can help:
.DS
$ bk clone -Mdev-tools bk://server/big-product
$ cd big-product
$ bk populate -Mdebugger
.DE
After running the above, the cached modules list will be
"dev-tools" and "debugger".
If you need to populate a module that is not present in your parent[s],
add one or more trailing urls (populate will use each url in turn until
all requested modules are found):
.DS
$ bk populate -Mblimey bk://uk-server/big-product
.DE
.LP
The set of modules populate will consider are specified on the command line with
.BR \-M ,
or retrieved from the cached modules list with
.BR \-r ,
or implied by the "default" modules database entry if neither of
the former apply.
.SH OPTIONS
.TP \-M\*<module\*>
.B \-l
Populate using hard links instead of copying the data.  
This is faster and saves disk space, but only works 
within filesystems supporting hard links.
.tp
.OPTreq \-M module
Add this module to the list of modules that should be
in this product instance.
This option may be repeated to add more than one module.
.tp
.B \-q
Run quietly.
.tp
.B \-r
Repair the product by replacing any components which listed in
the cached modules list that have been manually removed.
.SH "SEE ALSO"
.SA bkd
.SA clone
.SA parent
.SA relink
.SA triggers
.SA unpopulate
.SA url
.SH CATEGORY
.B Product
.SH AVAILABILITY
This command is an optional feature of \*[BK]
and must be enabled in your license.
To see if your license has this enabled, run 
.DS
bk lease renew
bk lease show
.DE
If the options field has "product" or "product-line" listed then your
license has this feature enabled.
If not, contact BitMover sales.
