.so ../bk-macros
.TH "bk pull" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    ============== Pulling changes into your repository ==============
.SH NAME
bk pull \- update a repository from its parent[s]
.SH SYNOPSIS
.Bc bk pull [\-iqRstu] [
.OPTreq \-r rev
.Bc ] [
.OPTequal \-E env var
.Bc ] [
.OPTreq \-c n
.Bc ] [
.ARGc parent
 ...\c
.B ]
.SH DESCRIPTION
.LP
Pull updates a repository from its incoming parent[s].
Changes are retrieved and automatically applied, if possible.
You will only be asked to resolve conflicts by hand if a file
has overlapping changes (changes where both repositories have
touched the same line in the same file).
.LP
To see what would be pulled run
.DS
bk changes -R
.DE
.LP
Pull normally runs resolve, the tool which applies the pulled changes,
automatically.  Resolve will look at each change, make sure there are
no conflicts that it can't merge, and apply the change.  You may have to
(or want to) run resolve manually.  If you do not want automatic merges,
i.e., you want to diff them by hand, then use the \-i option.  If resolve
was run automatically and it found conflicts, the changes have _not_ been
applied; you will need to run an interactive resolve to merge and
apply the changes.
.LP
You can override the default parent by specifying a different one.
Doing so changes the parent for the duration of this command only.
.LP
If you've pulled in error you may use bk unpull to remove the
changesets introduced by the pull.
Note! bk unpull will unpull the merge changeset, if any, discarding any
merge work you may have done.
.SH OPTIONS
.TP
.OPTreq \-c n
try to get the remote lock
.ARG n
times before giving up (default forever).
.tp
.OPTequal \-E env val
Export environment variable to remote site.
The environment variable must start with "BKU_".
.tp
.B \-i
Turn off automerge feature in resolve.
.tp
.B \-q
Be quiet.
.tp
.B \-R
Do not run resolve at all.  You must run 
.B bk resolve 
later.
.tp
.OPTreq \-r rev
Pull up to and including this revision.
(Or key or changeset revision. See 
.B bk help terms
under 'rev argument')
.tp
.B \-s
Pass 
.B \-s
to resolve (\c
.B \-s
means do not do interactive resolve of any conflicts, leave that for later.)
.tp
.B \-t
Pass 
.B \-t
to resolve (\c
.B \-t
means do not use the GUI tools.)
.tp
.B \-u
Do not complete the pull if there are local changesets, i.e., insist
that this operation is an update operation.
.SH "SEE ALSO"
.SA bkd
.SA parent
.SA push
.SA changes
.SA resolve
.SA triggers
.SA unpull
.SH CATEGORY
.B Repository
.br
.B Common
