.so bk-macros
.TH "bk push" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk push \- send local changes to the parent repository
.SH SYNOPSIS
.Bc bk push [\-aglnqt] [\-z[
.ARGc 0-9
.Bc ]] [
.OPTreq \-c n
.Bc ] [
.ARGc parent
.B ]
.SH DESCRIPTION
Push sends changes in the current repository back to its parent if
and only if the current repository is a superset of the parent.
When the parent has changes not found in the current repository,
push will fail and you will need to do a bk pull, merge those changes,
and retry the push.  The idea is that the parent is typically a shared
resource and should not be locked for merging.
.LP
If there is no new work in the parent, then all changes in the child
will be sent to the parent and auto\-applied.
.LP
You can override the default parent by specifying a different one.
Doing so changes the parent for the duration of this command only.
.LP
You can override the no\-merge policy by going to the parent and doing
a 
.B bk pull
and specify the child as the 
.BR bk\ parent .
.SH OPTIONS
.TP
.B \-a
If the parent is a superset of the current repository,
then automatically pull that work into the current repository.
.tp
.OPTreq \-c n
Try to get the remote lock 
.ARG n
times before giving up (default forever).
.tp
.B -g
Allow the use of GUI tools during the resolve (unlike resolve -t).
.tp
.B \-l
Do a long listing of changesets to be sent (like bk changes
does).  May be combined with 
.B \-n 
to get a repository difference summary.
.tp
.B \-n
Don't actually push, just show what would be pushed.
.tp
.B \-q
Run quietly.
.tp
.B \-t
Pass 
.B \-t
to resolve (
.B \-t
means do not use the GUI tools) during
the pull operation (requires 
.B \-a
and that the parent is a superset).
.tp
.OPTreq \-z d
Do compression at level 
.ARG d ,
if possible, where
.ARG d
is an integer value 0-9; default is 
.BR \-z6 .
Compression is possible when using ssh or the BK daemon,
but not with rsh.
.SH "SEE ALSO"
.SA pull 1
.SA parent 1
.SA resolve 1
.SA triggers 1
.SH AVAILABILITY
.\" lm, how's this?
.BU
\*(BK Professional allows communication via ssh, rsh,
and email as well as the bk daemon.
.br
.BU
\*(BK Professional will retry the operation automatically if
the remote host is busy.
.SH CATEGORY
.B Repository
