.so bk-macros
.TH "bk park" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk park \- temporarily save work
.SH SYNOPSIS
.Bc bk park [-lq] [
.OPTopt -p n
.Bc ] [
.OPTreq -y cmt
.B ]
.SH DESCRIPTION
Use bk park to temporarily save the state of work in progress.

The alternative is to clone the parent repository somewhere else
and do the bug fixes in that repository.
.SH OPTIONS
.if n .TP .8i
.if t .TP
.B \-l
list park files
.tp
.OPTreq \-p n
purge parkfile
.ARG n
.tp
.B \-q
quiet mode
.tp
.OPTreq \-y cmt
specify comment for park file
.SH "SEE ALSO"
.SA unpark 1
.SH CATEGORY
.B Repository
