.so ../bk-macros
.TH "bk path" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk path \- show the path that BK uses for all subprocesses
.SH SYNOPSIS
.B bk path
.SH DESCRIPTION
.LP
Mainly for debugging, 
.B bk path
displays the 
.V $PATH
that controls where \*(BK will look for commands.
.SH CATEGORY
.B Utility
