.so bk-macros
.TH "bk qs_setup" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== Quickstart Setup =======================
.SH NAME
bk Quickstart Setup
.SH DESCRIPTION
.LP
Here are examples on how to setup the initial repository, import from
plain files, a CVS repository, and/or an RCS repository. 
.LP
In order to do an import, the destination repository needs to exist. 
.B bk setup
is used when creating the first instance of a repository.
.sp
.DS
# Setup initial repository
cd ~/projects
bk setup test_package

# Import of plain files from a tar archive.  
# In order to do an import, the destination 
# repository needs to exist.  Notice that we put the 
# package in subdirectory, this is useful.
mkdir /tmp/gcc
cd /tmp/gcc
tar zxf /tmp/gcc-2.95.2.tgz
bk import -tplain /tmp/gcc ~/projects/test_package

# Import of a CVS tree which resides in /tmp/mycvsproject.
bk import -tCVS /tmp/mycvsproject ~/projects/test_package

# Import of a RCS tree which resides in /tmp/myrcsproject.
bk import -tRCS /tmp/myrcsproject ~/projects/test_package
.DE
.SH "SEE ALSO"
.SA quickstart 1
.SH CATEGORY
.B General
