.so bk-macros
.TH "bk qs_bkd" 1 20%E% "\*(BC" "\*(UM"
.\"    =================== Quickstart Admin =========================
.SH NAME
bk Quickstart Admin
.SH DESCRIPTION
.LP
Here are examples how to configure the bk daemon for both read-only and
read-write modes.  We show how to export all repositories on a system
in both read-write and read-only mode and we show how to export only
a specific repository in read-write and read-only mode.
.DS
# Configure \*(BK daemon for read-only 
# access for all repositories
bk bkd -d -xpush

# Configure \*(BK daemon for read-write 
# access for all repositories
bk bkd -d

# Access a specific repository when multiple 
# ones are being exported
bk clone bk://host.domain/some/dir/master ~/my_tree

# Configure a specific \*(BK repository 
# for read-write access
cd /master/repository
bk bkd -d -p6666 -xcd

# Configure a specific \*(BK repository 
# for read-only access
cd /master/repository
bk bkd -d -p4444 -xcd -xpush

# Access a repository bound to a specific port
bk clone bk://host.domain:6666 ~/my_tree
.DE
.SH "SEE ALSO"
.SA bkd 1
.SA quickstart 1
.SH CATEGORY
.B General
