.so bk-macros
.TH "bk r2c" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk r2c \- convert file revision to ChangeSet revision
.SH SYNOPSIS
.B bk r2c 
.OPTreq \-r rev 
\ 
.ARG file 
.SH DESCRIPTION
This command takes a revision and a filename and converts the specified
revision into the changeset revision which contains the file revision.
.SH "SEE ALSO"
.SA c2r 1
.SH CATEGORY
.B Utility
