.so ../bk-macros
.TH "bk root" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk root \- print the path name to the root of the repository
.SH SYNOPSIS
.B bk root
.[B] \-S
.[ARG] "directory \fB|\fP file"
.SH DESCRIPTION
This command prints the full pathname to the root of the repository.
The following commands are equivalent:
.DS
bk root
bk -P pwd
.DE
.LP
If a directory or file is specified,
.B bk root
will try to find the 
project root of that file or directory.
.LP
If
.B bk root
is run anywhere in nested collection, it will print the root of the
product.
To
print the root of a component use the 
.B -S
option.
.SH CATEGORY
.B Admin
