.so bk-macros
.TH "bk renames" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk renames \-list file renames contained in a changeset or range of changesets
.SH SYNOPSIS
.Bc bk renames -r
.ARG rev
.br
.Bc bk renames -r
.ARG rev,rev
.SH DESCRIPTION
.LP
Show a listing of files which have been renamed as
.br
.ARG oldname \ -> 
.ARG newname
.SH "SEE ALSO"
.SA renametool 1
.SH CATEGORY
.B File
