.so ../bk-macros
.TH "bk range" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk range \- demo program to show ranges & dates
.SH SYNOPSIS
.B bk range
.[B] \-q
[\c
.OPTreq \-c range 
|
.OPTreq \-r rev ]
.BKARGS
.SH DESCRIPTION
.LP
Many commands may take ranges of deltas as an argument.  A range is a
graphically contiguous region of deltas computed by taking the list
of upper bound and its ancestors and removing the lower bound and its
ancestors.
Deltas may be specified by their revision number (1.2), delta key
('amy@bitmover.com|man/man1/bk-terms.1|20020714011327|59990'), a
symbolic name (@tag), changeset rev (@1.33), or changeset key
(@'lm@disks.bitmover.com|ChangeSet|20020912140445|17593').  (see
.B bk help terms
for more info)
.LP
You may specify both end-points at once, or separately.
These are equivalent
.DS
bk log \-r1.3..1.5
bk log \-r1.3 \-r1.5
.DE
.LP
The result answers the question of "what is in the history of 1.5 that
is not in the history of 1.3?"
For example, if revision 1.2 forked 1.2.1.1 and 1.3, and 1.4 merged
in 1.2.1.1, then the range 1.3..1.5 expands to 1.2.1.1, 1.4, and 1.5.
.LP
You may specify dates instead of revisions like so
.sp
.DS
bk log \-c98..98
.DE
.LP
If there are two dates, or there is a date and a revision, then
the date format is [+\-]YYMMDDHHMMSS with missing fields either
rounded up or rounded down.
Rounding is explicit if there is a \*(lq+\*(rq (rounds up) or a
\*(lq\-\*(rq (rounds down) prefix on the date.
If there is no prefix, then the rounding is context sensitive.
If the date is the first date i.e., the starting point, then the
date is rounded down.
If it is the second date in the range, then it is rounded up.
So 98..98 is the same as 980101000000 .. 981231235959.
.LP
Note: the mixing of dates and revisions is deprecated.
.LP
If there is only one date specified, without a revision, then a 
very useful form of the date is to specify a recent period of time, 
such as 
.sp
.DS
bk log \-c\-1d
.DE
.LP
which will display the last 24 hours worth of changes.  This works
the same way for Years/Months/days/hours/minutes/seconds, i.e.,
.sp
.DS
In the last year:	log \-c\-1Y (or \-1y)
In the last month:	log \-c\-1M
In the last week:	log \-c\-1W (or \-1w)
In the last day:	log \-c\-1D (or \-1d)
In the last hour:	log \-c\-1h
In the last minute:	log \-c\-1m
In the last second:	log \-c\-1s
.DE
If you leave off the multiplier, 1 is assumed.
.LP
While you may not build up specific dates as \-1Y2m3d, you can specify 
fractions, i.e., to get the last 6 months worth, try
.DS
bk log \-c\-.5Y
.DE
.\" .LP
.\" You can mix and match revisions and date.  If you want everything in
.\" 98, but not past revision 1.5, you would type:
.\" .DS
.\" bk log \-c98 \-r1.5
.\" .DE
.LP
Dates can also be in the form of symbolic tags (ChangeSet file only).  
If you tagged a changeset with Alpha and another changeset with Beta,
you can type:
.DS
bk changes \-cAlpha..Beta
bk log -r@Alpha..@Beta foo.c
.DE
.LP
Ranges need not include both endpoints.  If you wanted to see everything
from Beta forward, you could type:
.DS
bk changes \-cBeta..
.DE
.LP
A single
.QR \-r ,
because it is the first revision seen, rounds down and means
1.1.  To get the most recent delta, type
.QR \-r+ .
.SH OPTIONS
.TP \-c\*<range\*>
.OPTreq \-c range
Specify deltas by a date range
.tp
.OPTreq \-r rev
Specify deltas by revision number
.tp
.B \-q
run quietly; default is to warn about all files which do not match the range
.SH EXIT STATUS
.LP
.B bk range
returns exit status:
.TP
0
on success.
.tp
1
on failure.
.SH "SEE ALSO"
.SA annotate
.SA co
.SA diffs
.SA log
.\" help://date
.\" help://dates
.\" help://ranges
.SH CATEGORY
.B Overview
.br
.B File
