.so bk-macros
.TH "bk rechksum" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk rechksum \- check and/or regenerate file checksums
.SH SYNOPSIS
.B bk rechksum [-cfov] 
.BKARGS
.SH DESCRIPTION
\*(BK has more integrity checksums than the original \*(SC had (it had one
over the whole s.file).  \*(BK maintains a checksum which is compatible with
\*(SC and also a set of new checksums, one per delta.  This command is used
to check and/or regenerate the per delta checksums.
.SH WARNING
The per delta checksums are part of the delta keys which are contained in 
the ChangeSet file.  These keys are part of the metadata which \*(BK uses
to group deltas into changesets.  If the checksums are changed, the checksums
in the ChangeSet file must be correspondingly changed, and the process
repeated for each copy of the repository.  Needless to say, we do not
encourage the use of this command with anything other than the
.B \-c 
option.
.SH OPTIONS
.TP
.B \-c
just check the checksums, do not do anything.
.tp
.B \-f
forcibly get the file and fix the checksums.
.tp
.B \-o
replace v2 checksums with v1 checksums 
.B (not recommended).
.tp
.B \-v
be verbose.
.SH "SEE ALSO"
.SA check 1
.SH CATEGORY
.B Admin
