.so ../bk-macros
.TH "bk rset" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk rset \- generate a \*(lqrelease set\*(rq
.SH SYNOPSIS
.B bk rset
.[B] \-ahS 
.if \n[NESTED] \{\
.[OPTreq] \-s alias
.\}
.OPTreq \-l rev
|
.OPTreq \-r rev 
|
.OPTreq \-r r1
.OPTreq \-r r2
.SH DESCRIPTION
.B bk rset
is used to generate a view of either the changes contained in a particular
changeset, the changes contained in a sequence of changesets, or a view
of the entire repository as of a particular changeset.
.LP
To see the changes made by a particular change, try
.DS
$ bk rset -r1.201
ChangeSet|1.200..1.201
src/gui/fmtool.tcl|1.17..1.21
.DE
.B Note:
the first revision listed in the 1.17..1.21
is the revision of the last delta created before the start of the
specified changeset.  It is done this way so that programs which
parse this output know where the last changeset stopped.  It is also
worth noting that \*(BK changesets can contain multiple revisions to 
the same file, which is why the end of the last changeset and the start
of the requested changeset is listed in the output.
.SH OPTIONS
.TP "\\fB\\-\\-standalone \\fP"
.B \-a
show deleted files which are normally suppressed.
.tp
.B \-h
show the \*(lqhistoric\*(rq paths of the file as well as the current path.
This makes the output look like
.ARGc current
|\c
.ARGc start
|\c
.ARGc rev
|\c
.ARGc end
|\c
.ARG rev .
The output has three file names:  current, starting, and ending; 
corresponding to the current pathname,
the pathname of the file at the start of the first changeset listed, 
and the pathname of the file at the end of the last changeset.
.tp
.OPTreq \-l rev
list the entire repository as of changeset 
.ARG rev .
Mutually exclusive with
.QR \-r .
.tp
.OPTreq \-r rev
specify the changeset revision to show.  This will show all the files
changed in this changeset.
.tp
.OPTreq \-r r1 \ \fB\-r\fP\*<r2\*>
If two revisions are specified, 
the two revs specify the changeset range to show.
The files included will be all files changed after the changeset specified
by the first rev, up to and including the changeset specified by the
second rev.
.if \n[NESTED] \{\
.tp
.B \-S
.tp
.B \-\-standalone
Just run rset on the current component.
This has no effect in a traditional standalone repository,
but in a nested collection, processes just the current component
and not the entire nested collection.
.tp
.OPTreq \-s alias
In a nested collection,
.B rset
can recurse into some or all of the populated components.
Using the 
.OPTreq \-s alias
option limits the repositories processed to those specified by
.ARG alias .
If this option is repeated the implied subset is the union of all
specified components.
If no
.ARG alias
is specified that is taken to be the same as
.BR \-sHERE .
.\}
.SH "SEE ALSO"
.SA export
.SA log
.BR diff (1),
.BR patch (1),
.SH CATEGORY
.B Utility
