.so ../bk-macros
.TH "bk rm" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME 
bk rm \- remove \*(BK file[s]
.SH SYNOPSIS
.B bk rm
.[B] \-f
.ARG file
.FILES
.SH DESCRIPTION
.LP
To delete a file, do this:
.DS
$ bk rm foo.c
.DE
Removing the file actually moves it to the
.B BitKeeper/deleted/
directory.
All future operations will ignore the file unless you name it
explicitly, but it will still exist in the repository and will still be
propagated by 
.B bk pull
and/or
.BR "bk push" .
Edited files may not be deleted, you must check them in first.
.LP
If you wish to obliterate all traces of a file, use the 
.B bk gone
facility.
.LP
To resurrect the file, use bk unrm.
.DS
bk unrm foo.c
.DE
.SH NOTES
.B bk rm
will not remove directories, use
.B bk rmdir
for that.
.LP
.B bk rm
will refuse to remove \*[BK] metafiles without the 
.Q \-f
option (the use of which is not recommended except in the case of triggers).
.SH SEE ALSO
.SA gone
.SA rmdir
.SA unrm
.SH CATEGORY
.B Common
.br
.B Repository
