.so ../bk-macros
.TH "bk renumber" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk renumber \- regenerate the revision history numbers
.SH SYNOPSIS
.B bk renumber
.[B] \-nq 
.BKARGS
.SH DESCRIPTION
This command exists primarily because Sun's Teamware had some bugs at one 
point and put nonsensical revision numbers in the s.files.  Fortunately,
\*(SC does not really care about the revision numbers, it maintains
the graph structure elsewhere.  This program uses that other information
to start over and renumber the entire graph.
.SH OPTIONS
.TP
.B \-n
do not do anything, dry run.
.tp
.B \-q
be quiet.
.SH CATEGORY
.B Utility
