.so ../bk-macros
.TH "bk root" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk root \- print the path name to the root of the repository
.SH SYNOPSIS
.Bc bk root [
.ARG directory 
.B |
.ARG file ]
.SH DESCRIPTION
This command prints the full pathname to the root of the repository.
The following commands are equivalent:
.DS
bk root
bk -R pwd
.DE
.LP
If a directory or file is specified, bk root will try to find the 
project root of that file or directory.
.SH CATEGORY
.B Admin
