.so bk-macros
.TH "bk smerge" 1 2001/08/28 "\*(BC" "\*(UM"
.SH NAME
bk smerge \- smart text-based 3-way file merge
.SH SYNOPSIS
.\"
.Bc bk smerge [\-2efghns] [
.OPTreq \-A n
.Bc ] [
.OPTreq \-a n
.Bc ] [
.OPTreq \-r r
.B ] 
.ARG local
.ARG gca
.ARG rem
.ARG file
.SH DESCRIPTION
This command does a smart 3-way file merge.
.SH OPTIONS
.if t .TP .6i
.if n .TP 1i
.B \-2
Enable the 2 way output format (like diff3)
.tp
.B \-g
Enable 'gca' output format that show the local and
remote files like a unified diff between the GCA and that file.
This is the recommended output format, but not the default becauses
it confuses people the first time they see it.
.tp
.B \-n
Enable the 'newonly' output format.  (like
.B \-2
except it marks added lines)
.tp
.B \-e
Print examples of all 4 output formats from 
.B smerge
.tp
.OPTreq \-a n
Enable a list of merge functions seperated by commas.  'all' will enable
all automerge algorthms.   Use 'bk smerge -h' to find the algorthms enabled by
default.
.tp
.OPTreq \-A n
Display a list of merge functions seperated by commas.  See \-a.
\-Aall will turn off all automerging.
.tp
.B \-f
Enable fdiff output.  (Used internally by 
.Bc fm3tool
)
.tp
.B \-s
Show sequence numbers in output
.tp
.tp
.OPTreq \-r range
When given a range of the format 'start..end' it limits the output to
just the sequence numbers after (not including) 'start' and before (not 
including) 'end'.  start or end can be omitted to go to the end of the file.
.SH EXIT STATUS
0 for no conflicts, 1 for conflicts, 2 for errors.
.SH "SEE ALSO"
.BR diff3 (1)
.br
.SA merging 1
.SA resolve 1
.SA merge 1
.SH CATEGORY
.B Utility
