.so ../bk-macros
.TH "bk stripdel" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk stripdel \- strip deltas out of an s.file
.SH SYNOPSIS
.B bk stripdel
.[B] \-bCcdq
.[OPTreq] \-r rev
.ARG filename
.SH DESCRIPTION
The 
.B bk stripdel
command is used to \*(lqstrip\*(rq deltas from a revision history.  The
deltas, once stripped, are not recoverable.  
.LP
This command is typically called by the 
.B bk clone
or the 
.B bk undo
commands, and perhaps the
.B bk import
command.
It can be called directly if you wish to remove certain deltas from a
file.
.LP
The 
.B bk stripdel
command will fail if the specified revisions are included in a changeset
and the 
.Q \-C 
option is not present.
.SH WARNING
It is an extremely bad idea to use the 
.Q \-C
option, it can corrupt your repository.  Instead, consider the 
.Q \-x
option of
.BR "bk co" .
.SH OPTIONS
.TP \-r\*<rev\*>
.B \-C
Do not respect cset boundaries, used by 
.BR "bk undo" .
.tp
.B \-c
Checks if the specified rev[s] can be stripped but do not strip them.
.tp
.B \-d
Strip deltas which are part of a
.SB MONOTONIC
file.
.tp
.B \-q
Run quietly.
.tp
.OPTreq \-r rev
Set of revisions to be removed.
.SH "SEE ALSO"
.SA admin
.SA clone
.SA co
.SA undo
.SH CATEGORY
.B File
