.so bk-macros
.TH "bk sccslog" 1 20%E% "\*(BC" "\*(UM"
.SH NAME 
bk sccslog \- like prs, except it sorts deltas by date across all files
.SH SYNOPSIS
.Bc bk sccslog [\-ACpv] [
.OPTreq \-c dates
.Bc ] [
.OPTreq \-i d
.Bc ] [
.OPTreq \-r r
.B ]
.BKARGS
.SH DESCRIPTION
.LP
.B sccslog
displays part or all  of  the  SCCS  file in a user supplied format.
.SH OPTIONS
.if t .TP .6i
.if n .TP 1i
.B \-A
Select all uncommited deltas in a file.
.tp
.OPTreq \-c dates
Cut off dates.  See Range Specifications (below) or
._SA range 
for details.
.tp
.B \-C
Produce comments for a changeset.
.tp
.OPTreq \-i d
Indent output by 
.ARG d
spaces.
.tp
.B \-p
Show basenames instead of full pathnames.
.tp
.OPTreq \-r r
Specify a revision or a part of a range.
.tp
.B \-v
Be verbose about errors and processing.
.LP
Note that
.ARG date
may be a symbol, which implies the date of the delta which matches the symbol.
.LP
Range specifications:
.if t .TP 1.2i
.if n .TP 1.5i
.I \-r+
prints the most recent delta
.tp
.I \-r1.3..1.6
prints all deltas 1.3 through 1.6
.tp
.I \-d9207..92
prints all deltas from July 1 '92 to Dec 31 '92
.tp
.I \-d92..92
prints all deltas from Jan 1 '92 to Dec 31 '92
.SH CATEGORY
.B Basics
