.so ../bk-macros
.TH "bk support" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk support \- send a support request
.SH SYNOPSIS
.B bk support
.[B] \-T
.SH DESCRIPTION
.LP
Send a request to \*[BM] support.
.LP
The default behavior is to display the graphical version of the support
form when the
.SB DISPLAY
environment variable is set (\*[UN]) or if it is
run on a Windows operating system.
To use a text editor rather than the GUI, use the
.Q \-T
option.
.LP
This command can be used to request support instead of
mailing to
.BR support@bitkeeper.com .
The advantage is that it automatically includes the version of \*(BK
and the operating system being used, which speeds the ability of the
support team to respond to the request.
.SH OPTIONS
.TP
.B \-T
Use a text editor rather than the default graphical tool to fill out a support
report.
.SH EXAMPLE
An example text template looks like this:
.sp
.nf
Program:
        [cset, co, ci, etc.  or what you were doing, like 'installing']

Release:
        beta10-pre1

OS:
        [Linux, IRIX, NT, etc]
Etc.
.sp
.fi
and the filled out report should look like this (note that the data
goes after the tags, not on the same line):
.sp
.nf
Program:
        support

Release:
        pre-2.0-2

OS:
        All
Etc.
.sp
.fi
.SH CATEGORY
.B Admin
