.so ../bk-macros
.TH "bk sfiles" 1 %E% "\*(BC" "\*(UM"
.\"    ======================== Sfiles Help ===========================
.SH NAME
bk sfiles \- generates lists of revision control files
.SH SYNOPSIS
.Bc bk [-r] sfiles [\-1acCdDeEgGjlnSuUvx] [
.OPTreq \-o file
.Bc ] [
.OPTopt \-p A|C
.Bc ] [
.ARGc dirs
.B ]
.SH DESCRIPTION
.B bk sfiles
is used to generate lists of revision control files, files related to
revision control files, directories related (or not) to revision control files,
and/or files not under revision control.  In other words, if you need a list
of files, you've come to the right place.
.LP
.B bk sfiles 
without any arguments finds all s.files in or below the current working
directory.  This is what
.B bk\ \-r\ \c
.ARG command
uses to generate the list of files to feed to 
.ARG command .
.LP
If a directory and/or file list is specified, then each of the items in 
the list is processed; directories are processed recursively.
.SH OPTIONS
When examining the options, bear in mind that if you want a list of files
in one particular state, do not combine the option which specifies that
state with options which specify different states; you'll get one list 
with both kinds of files if you do.
.LP
If you want a one pass with different sorts of files listed, look at
the 
.B \-e/E/v
options.
.if n .TP 1i
.if t .TP .6i
.B \-1
Only examine one directory level.  Do not go into subdirectories.
.tp
.B \-a
Examine all files, even if listed in BitKeeper/etc/ignore.
.tp
.B \-c
List changed files (locked and modified).
If clock_skew is set in the config file then the file timestamps
and other attributes are used to speed scanning.
The acceptible clock skew can be configured, see 'clock_skew' in
bk help config-etc.
.tp
.B \-C
Identical to 
.B \-c
except the timestamp DB is not consulted.
.tp
.B \-d
List directories under \*(BK control (SCCS subdir exists).
.tp
.B \-D
List directories with no (or empty) SCCS subdirs.
.tp
.B \-e
Shorthand for 
.B \-dDGjluvx
.tp
.B \-E
Shorthand for 
.B \-cdDGjlnuvxp
.tp
.B \-g
List the gfile name, not the sfile name.
.tp
.B \-G
List files if and only if they are checked out ("gotten").
.tp
.B \-j
List junk files, i.e., files in \*(SC subdirectories which are not 
metadata.
.tp
.B \-l
List locked files (p.file and/or z.file).
.tp
.B \-n
List s.files that are not in the correct location.  (Must be run from
repository root, bk -r sfiles -n.)
.tp
.OPTreq \-o file
Send output to
.ARG file
and progress information to stdout.
.tp
.OPTopt \-p A|C
List files with pending deltas.  If 
.B \-pC
then list 
leaves which are not in a changeset as 
.B file|1.3
If
.BR \-pA ,
that implies 
.BR \-pC ,
and 
lists all revisions, not just the tip.
.tp
.B \-P
Like -p, but don't trust the d.file.  Use the s.file for verification
and create or delete the d.file to match the status of the s.file.
.tp
.B \-S
Produce a summary listing only, typically combined with 
.BR \-E .
.tp
.B \-u
List unlocked files.
.tp
.B \-U
List user files only, skipping 
the ChangeSet file 
and everything below
.B BitKeeper/
other than 
.BR BitKeeper/triggers/* .
.tp
.B \-v
Prefix the output with information about the state of the s.file.
The information is in a 6 character field, followed by a space,
then followed by the filename.  Each of the columns are described
below, with the notation, then the option, then description.
.RS
.tp 1.4i
\f(CBl-----\fR\ \ (-l)
the file is locked
.tp
\f(CBu-----\fR\ \ (-u)
the file is unlocked
.tp
\f(CB-c----\fR\ \ (-c)
the file is modified (changed)
.tp
\f(CB--p---\fR\ \ (-p)
the file has pending deltas
.tp
\f(CB---G--\fR\ \ (-G)
the file is checked out i.e., "gotten"
.tp
\f(CB----n-\fR\ \ (-n)
the file is not in its recorded location
.tp
\f(CB-----d\fR\ \ (-d)
a directory containing \*(BK files
.tp
\f(CB-----D\fR\ \ (-D)
a directory containing no \*(BK files
.tp
\f(CBjjjjjj\fR\ \ (-j)
the file is junk
.tp
\f(CBxxxxxx\fR\ \ (-x)
file is not yet under \*(BK control
.RE
.tp
.B \-x
List files which have no revision control files.
.SH NOTES
.LP
.B bk sfiles
will not descend into directories containing a
.B .bk_skip
file.  This allows you to prune entire subtrees from processing.
.LP
Files under BitKeeper/{log,readers,writers}/ are always ignored.
.LP
Revision control files must look like SCCS/s.*,
not foo/bar/blech/s.*
.SH "SEE ALSO"
.SA history 1
.br
.SA ignore 1
.br
.SA new 1
.SH CATEGORY
.B File
.\" help://Files/gfiles
