.so ../bk-macros
.TH "bk superset" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk superset \- check to see if the parent is ahead of the current repository
.SH SYNOPSIS
.B bk superset
.[B] \-q
.[ARG] parent
.SH DESCRIPTION
.LP
superset does checks to see if removing the current repository is a lossless
event. 
.LP
It checks that:
.LP
.li
there are no local only changesets and/or tags
.li
there are no pending deltas
.li
there are no modified files
.li
there are no extra files
.\" .li
.\" there are no parked files
.li
there are no pending patches from aborted pulls
.li
there are no unresolved pulls
.li
there are no saved patches from a
.B bk collapse
operation
.li
there are no saved patches from an undo/unpull operation
.li
if there are subrepositories and 
.B no parent was specified 
in the call to 
.BR "bk superset" ,
then the subrepositories are also similarly checked against their parent
.LP
Unless the
.Q \-q
option is present superset lists all things which are not
in the parent.
.SH OPTIONS
.TP
.B \-q
Be quiet
.SH "EXIT STATUS"
.LP
superset exits 0 if the parent is a superset, 1 if the parent is not.
.SH CATEGORY
.B Repository
