.so bk-macros
.TH "bk send" 1 20%E% "\*(BC" "\*(UM"
.\"    =============== Sending BitKeeper patches ===============
.SH NAME
bk send \- send a \*(BK patch
.SH SYNOPSIS
.Bc bk send [\-dfq] [\-w[
.ARGc Wrapper
.Bc ]] [
.OPTreq \-r revs
.B ]
.ARG user@host.com "| \-"
.SH DESCRIPTION
.LP
The bk push/bk pull interface is the easiest 
way to keep two repositories synchronized, however,
if your only connection to the remote machine is through
email, use bk send.
.LP
To send the whole repository, do:
.DS
$ bk send user@host.com
.DE
.LP
\*(BK will generate the (huge) patch and mail it to user@host.com.
.LP
If you happen to know that you want to send a specific change (and
you know that the other repository has the changes leading up to the
change you want to send), you can do this:
.DS
$ bk send \-rbeta.. user@host.com
.DE
.LP
or
.sp
.DS
$ bk send \-r1.10.. user@host.com
.DE
.LP
Send remembers the changesets it has sent in BitKeeper/log/sendlog\-\<address\>
where \<address\> is like user@host.com.  When you don't specify a list
of changesets to send, "send" will look in the log file and send only the
new changesets.  So the easiest thing to do is to always use the same
email address and just say:
.DS
$ bk send user@host.com
.DE
.LP
If you lose the log file and you want to seed it with the changes you
know have been sent, the command to do that is:
.DS
$ cd to package root
$ bk prs \-h \-r\<revs\> \-d:KEY: ChangeSet \> BitKeeper/log/send\-user@host.com
.DE
.LP
You can wrap patches so that they do not get corrupted by mailers.
We currently support wrapping with uuencode.  The following (contrived)
command sends a wrapped patch and applies it in /tmp/foo (which must
exist):
.DS
$ bk send \-wuu \-r..1.5 - | bk receive /tmp/foo
.DE
.SH OPTIONS
.if t .TP .75i
.if n .TP 1.25i
.B -d
Prepend the patch with unified diffs.  This is because some
people like looking at the diffs to decide if
they want the patch or not.
.tp
.B \-f
send the patch even if \*(BK believes the remote repository is up to date.
.tp
.B -q
Be quiet.
.tp
.OPTreq -r revs
Specify the list of changesets to send.
.tp
.OPTreq -w Wrapper
Wrap the patch with 
.ARG Wrapper
before sending it.
.SH "SEE ALSO"
.SA ranges 1
.SA receive 1
.SA resync 1
.SA wrap 1
.SH CATEGORY
.B File
