.so ../bk-macros
.TH "bk setup" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper setup ======================
.SH NAME
bk setup \- create a new \*(BK package
.SH SYNOPSIS
.B bk setup
.[OPT] -fp
.[OPTreq] \-F key\fB=\fIval
.[OPTreq] \-c config_file
.ARG directory
.SH DESCRIPTION
There is a graphical version of this command,
.BR "bk setuptool" .
.LP
To set up a \*(BK package, you need to create and populate an initial tree.
The 
.B bk setup 
command will create a mostly empty package tree containing a
few files and directories that are used by \*(BK.
.LP
The setup command will prompt you for a description of the package as
well as other information about your new package.
.LP
A system wide default config template file may be created in either
.B $HOME/.bk/config.template 
or in
.B /etc/BitKeeper/etc/config.template
or in
.BR \`bk\ bin\`/etc/config.template .
If this file is detected when 
.B bk setup
is run, without the
.B \-c
option, it will be used as the default
.B BitKeeper/etc/config
file automatically.
The first file found is used.
.SH OPTIONS
.TP 16
.OPTreq \-c config_file
Use 
.ARG config_file
as the configuration file to setup the repository.
.tp
.B \-f
Don't ask for confirmation.
.tp
.OPTreq \-F key\fB=\fIval
Override default values for the specified field.
Typically used in combination with a config template.
.tp
.B \-p
print the field names to stdout (used by setuptool).
.SH EXAMPLES
.LP
When creating a repository called "mypackage", you type
the following command:
.DS
$ bk setup ~/mypackage
.DE
The following shows the directory structure of a new package.
.TP 16
.B mypackage/
.RS 8
.TP 18
.B ChangeSet
Index of all changes to the repository.
.tp
.B BitKeeper/
Directory where administrative files are kept.
.RE
.RS 16
.TP 10
.B etc/
Config files, in the future, policy files.
.tp
.B log/
Mail and command logs, parent pointer.
.tp
.B deleted/
Deleted files are archived here (like CVS Attic).
.tp
.B tmp/
Scratch area.
.tp
.B readers/
Transient directory for reader locks.
.tp
.B writer/
Transient directory for writer lock.
.tp
.B triggers/
Executable trigger programs stored here.
.RE
.LP
Once the repository is created, you should make a hierarchy to store
your source files. For example, you could create the following tree:
.TP
.B mypackage/
.RS 8
.TP 18
.B src/
source code
.tp
.B man/
manual pages
.tp
.B doc/
user guides, papers, docs...
.RE
.LP
At this point, if you are creating a new package from scratch, 
cd to
.B ~/mypackage/src
and start creating files.  See 
.B bk help Basics-Overview
and
.B bk help Howto-setup
for more info.
.LP
If you have an existing set of files that you want to add to the
repository, see 
.BR "bk import" .
.SH "SEE ALSO"
.SA Howto
.SA Howto-setup
.SA config-etc
.SA import
.SA license
.SA setuptool
.SH CATEGORY
.B Repository
