.so ../bk-macros
.TH "bk status" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    =============== Getting BitKeeper status ===============
.SH NAME
bk status \- show repository status
.SH SYNOPSIS
.B bk status
.[ARG] repository
.SH DESCRIPTION
.LP
The 
.B bk status
command gives a quick overview of the tree. 
The default output looks something like:
.DS
Status for \*(BK repository /u01/package/bk
\*(BK version is bk-beta-14.3 20000302045832 for x86-linux
Built by: lm@work.bitmover.com
Built on: Wed Mar  1 21:22:07 PST 2000
Parent repository is bitmover.com:/home/bk/one
Pending patches
    61 people have made deltas.
   600 files under revision control.
     3 files not under revision control.
     0 files modified and not checked in.
     0 files with checked in, but not committed, deltas.
.DE
.SH EXIT STATUS
.LP
.B bk status
returns exit status:
.TP
0
on success.
.tp
1
on failure.
.SH SEE ALSO
.SA sfiles
.SH CATEGORY
.B Repository
