.so ../macros
.TH "bk status" 1 08/18/00 "*(BC" *(BK
.\"    =============== Getting BitKeeper status ===============
.SH NAME
bk status \- show repository status
.SH SYNOPSIS
.if t \{\
.B bk status [\-v] [
.IB repository ]
.\}
.if n
bk status [\-v] [<repository>]
.SH DESCRIPTION
.LP
The status command tells you what is going in the the tree.  The default
output looks something like:
.AX
Status for BitKeeper repository /u01/package/bk
BitKeeper version is bk-beta-14.3 20000302045832 for x86-linux
Built by: lm@work.bitmover.com
Built on: Wed Mar  1 21:22:07 PST 2000
Parent repository is bitmover.com:/home/bk/one
Pending patches
    61 people have made deltas.
   600 files under revision control.
     3 files not under revision control.
     0 files modified and not checked in.
     0 files with checked in, but not committed, deltas.
.XA
.SH OPTIONS
.TP
.B \-v	
Verbose listing.  Lists users, files not under
revision control, files modified and not checked in, and
files with checked in, but not committed deltas, one per line.
.SH CATEGORY
.B Repository
