.so ../bk-macros
.TH "bk tag" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper tags ======================
.SH NAME
bk tag \- tag the \*(BK repository with a symbolic name
.br
bk tags \- list tagged changesets
.SH SYNOPSIS
.Bc bk tag [
.OPTreq \-r rev
.B ] 
.ARG symbol
.SH DESCRIPTION
.LP
Tags (aka symbols or labels) are used when you want to record the state of 
a tree.  It is quite common to ``tag the tree'' with a release name when 
shipping a product to customers.  
.LP
To add a tag to the repository, make sure that you've checked everything
in and created a changeset.  You can use bk status to see what needs to
be checked in and/or committed to a changeset. Tag the tree by typing:
.DS
$ bk tag Alpha
.DE
The Alpha tag will be set on the most recent changeset.  Or you
can commit a changeset and tag the tree at the same time with the \-S
option to commit:
.DS
$ bk commit \-SAlpha
.DE
To see all the tagged changesets run
.DS
$ bk tags
.DE
which is just an alias for 
.DS
$ bk changes -t
.DE
If you want to recover the state of the world as of a tag, do this:
.DS
$ bk clone \-rAlpha source_repository Alpha
.DE
which will create a repository which has everything up to and including
the Alpha changeset.
.LP
If you discover that you should have tagged a changeset after more
changesets have been added to the repository, use the 
.B \-r 
option to
select the proper changeset.  You can find out which revision to tag
by running 
.BR bk\ changes .
.LP
A frequent problem is that you tag a changeset with "Done" and then
discover you aren't done.  You may update the tag to the later changeset
by running the 
.DS
$ bk tag Done 
.DE
command again.  If there are multiple tags
with the same name, \*(BK takes the most recently applied tag (which
means you can move a tag backwards by specifying an older revision of
the cset file).
.SH LEGAL TAGS
Certain characters are not allowed in tags because they conflict with
other parts of the \*(BK revision, date, and/or range namespaces.
Tags may not start with digits, an equal sign "=", a hyphen "-", or a dot
".".
A tag may not be the plus sign "+" since that is used to mean the most
recent revision.
A tag may not contain the strings "..", ".,", ",.", or ",,"
since those are used to specify ranges.
Tags may not contain any of the following characters: Control-A "^A",
vertical bar "|", newline "\\n", or carriage return "\\r".
.SH BUGS
.LP
Need a way of setting a tag in citool.
.SH "SEE ALSO"
.SA admin
.SA changes
.SA commit
.SA prs
.\" help://tags
.\" help://label
.\" help://labels
.SH CATEGORY
.B Repository
