.so bk-macros
.TH "bk tag" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper tags ======================
.SH NAME
bk tag \- tag the \*(BK repository with a symbolic name
.SH SYNOPSIS
.Bc bk tag [
.OPTreq \-r rev
.B ] 
.ARG symbol
.SH DESCRIPTION
.LP
Symbols (aka tags) are used when you want to record the state of a tree.
It is quite common to ``tag the tree'' with a release name when shipping
a product to customers.  
.LP
To add a tag to the repository, make sure that you've checked everything
in and created a changeset.  You can use bk status to see what needs to
be checked in and/or committed to a changeset. Tag the tree by typing:
.DS
$ bk tag Alpha
.DE
The Alpha symbol will be set on the most recent changeset.  Or you
can commit a changeset and tag the tree at the same time with the \-S
option to commit:
.DS
$ bk commit \-SAlpha
.DE
If you want to recover the state of the world as of a tag, do this:
.DS
$ bk clone \-rAlpha source_repository Alpha
.DE
which will create a repository which has everything up to and including
the Alpha changeset.
.LP
If you discover that you should have tagged a changeset after more
changesets have been added to the repository, use the 
.B \-r 
option to
select the proper changeset.  You can find out which revision to tag
by running 
.BR bk\ changes .
.LP
A frequent problem is that you tag a changeset with "Done" and then
discover you aren't done.  You may update the tag to the later changeset
by running the 
.DS
$ bk tag Done 
.DE
command again.  If there are multiple tags
with the same name, \*(BK takes the most recently applied tag (which
means you can move a tag backwards by specifying an older revision of
the cset file).
.LP
Tagging individual files, while possible with the admin command, is
generally unnecessary.  However, if you want to tag all the files,
you can do so like this:
.DS
$ bk \-r admin \-SAlpha
.DE
That will put the Alpha tag on top of trunk on all files.
.SH BUGS
.LP
Need a way of setting a tag in citool.
.SH "SEE ALSO"
.SA admin 1
.SA changes 1
.SA commit 1
.SA prs 1
.SH CATEGORY
.B Repository
