.so bk-macros
.TH "bk takepatch" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper takepatch command ======================
.SH NAME
bk takepatch \- apply a \*(BK patch
.SH SYNOPSIS
.Bc bk takepatch [\-acimStv] [\-f[ 
.ARGc file
.B ]]
.SH DESCRIPTION
.LP
The takepatch command is used to apply a \*(BK patch.  \*(BK patches
are how data is moved between \*(BK repositories.
.LP
Users do not normally invoke this command, it is called directly by 
.BR bk\ pull ,
.BR bk\ push ,
.BR bk\ resync ,
or
.BR bk\ receive .
.SH OPTIONS
.if t .TP
.if n .TP 1i
.B \-a
Apply the changes (call 
.BR bk\ resolve .)
.tp
.B \-c
Do not accept conflicts with this patch.
.tp
.OPTreq \-f file
Take the patch from 
.ARG file
and do not save it.
.tp
.B \-i
Initial patch, create a new repository.
.tp
.B \-m
List deltas as they are read in the patch.
.tp
.B \-S
Save RESYNC and or PENDING directories even if errors.
.tp
.B \-t
Run in text only mode, do not talk to X11.
.tp
.B \-v
Verbose level, more is more verbose, \-vv is suggested.
.SH "SEE ALSO"
.SA pull 1
.SA push 1
.SA receive 1
.SA resync 1
.SH CATEGORY
.B Repository
