.so bk-macros
.TH "bk terms" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk terms \- definitions of \*(BK terms
.SH DESCRIPTION
.LP
.SS "\*(BK definitions:"
.if t .TP
.if n .TP 4
.B sfile
A file containing the revision history, e.g., SCCS/s.foo.c
.tp
.B gfile
A file that is checked out, e.g., foo.c
.tp
.B package
A package is a logical concept while the repository is 
the physical instance of that concept. A package is 
created only once when the 
.B bk setup
program is run.
.tp
.B repository
A directory tree that is populated with the revision
control files.  A repository is an instance of a
package i.e. there is one package, but there can
be many repositories belonging to that package.
.tp
.B tag, symbol
A symbolic name (or tag) which is given to a particular
revision of one or more files.  e.g., "Alpha1".
.tp
.B revision, delta (files)
One version of a particular file, or one change to a
particular file, depending on context.  Sometimes we
want to talk about the way the file is while sometimes
we want to talk about how it got there.
Files that have been checked out, edited, and not
yet checked back in are "modified" files.  When you
check files in, the modifications become new deltas.
.tp
.B ChangeSet
The file used to record the repositories' history of changes.
.tp
.B cset, changeset
A particular change to a repository consisting of one or
more changes to one or more files.
.tp
.B changeset number
Revision number for a changeset.  These numbers fluctuate, 
but stabilize, over time.  If you want an immutable, unique reference
for a changeset, use the changeset key.
.tp
.B changeset key
A unique, unchanging identifier for a changeset which may be
used anywhere a normal revision number and/or symbolic tag is used.
A particular changeset key may be extracted with
.DS
bk -R prs -hr<rev> -nd:KEY: ChangeSet
.DE
.tp
.B identity
Each repository family has an identity unique to that repository family.
Updates will fail if the two repositories do not have the same identity.
.tp
.B pending
Deltas which have been checked into a file but not yet
committed to a changeset.
.tp
.B patch
Formally, this is one or more changesets wrapped up
for transmission to someone else.  It is similar to
what you may be used to thinking of as a patch
(a list of all the changes between two versions of
an entire package) but carries more information: who
made the changes, when, and why.
.tp
.B Trunk
Main line source base.  In \*(BK revtool, the trunk is the X.Y in the 
graph, branches are X.Y.Q.Z, which always get merged into the trunk.
.tp
.B Tip
Latest revision on some branch, usually the trunk.
.tp
.B Top of Trunk (TOT)
The latest revision on the trunk.
.\".tp
.\".B Line of Development (LOD)
.\"Another trunk in a repository.
.SH NOTES
We attempt to list all of the \*(BK definitions here, but send us a
message at "docs@bitkeeper.com" if you have suggestions for definitions
we may have missed.
.SH CATEGORY
.B Overview
