.so bk-macros
.TH "bk triggers" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk triggers \- using \*(BK event triggers
.SH DESCRIPTION
.LP
\*(BK supports a variety of trigger types. Triggers are 
arbitrary commands which run before or after a repository 
level command.  These triggers can be used for event notification 
and/or to implement control over the events.
.LP
There are three event classes which activate triggers: incoming
events, outgoing events, and commits.
.LP
Incoming events are triggered by a pull into a repository or
another repository doing a push into a repository.
.LP
Outgoing events are triggered by a push from a repository, another 
repository doing a pull from a repository, or when a repository 
is cloned.
.LP
Triggers can be structured to run in all copies of a project 
and/or in a specific instance of a project.
.LP
A trigger is a program, usually a shell script but it can be
any sort of executable program, placed in the BitKeeper/triggers
subdirectory.  There are three triggers, corresponding to the
event class, each of which can be called before or after the
event:
.DS
BitKeeper/triggers/pre\-commit
BitKeeper/triggers/post\-commit
BitKeeper/triggers/pre\-incoming
BitKeeper/triggers/post\-incoming
BitKeeper/triggers/pre\-outgoing
BitKeeper/triggers/post\-outgoing
.DE
.sp .1i
When a trigger is called, it is called at the root of the
repository.  Triggers are easily customized on a per repository
basis, for example:
.DS
#!/bin/sh

if [ `pwd` = /home/bk/stable ]
then	echo whatever | mail \-s 'event in stable' lm
fi
.DE
Both pre and post triggers are called with the command line which
started the trigger, somewhat like this:
.DS
pre|post this:/repository command args
.DE
The pre\-triggers can be used to control events within a repository.
If the pre\-trigger exits with a non\-zero exit status, the event will
not be executed.  Ideally, this could be used to implement some sort
of process control, such as insisting on a bug id before a commit.
.LP
The post\-triggers are typically used for event status.  They are
called with command\-line arguments and with the status stored in 
the appropriate environment variable:
.RS .5i
.nf
.ps -1
.B BK_INCOMING
.ps -1
.B BK_OUTGOING
.ps -1
.B BK_COMMIT
.fi
.RE
Possible values for the variables:
.TP 1.2i
.B OK
Changesets were moved into this repository
.tp
.B NOTHING
There was nothing to do, i.e., a pull was
executed, but the from repository had no new work.
.tp
.B DRYRUN
There was something to do but it was not
actually done.
.tp
.B CONFLICTS
A push was attempted but there were changesets in the
destination which were not in the source.
.tp
.B SIGNALED	
A helper process died with a signal.
.SH EXAMPLES
.LP
These are real examples from the \*(BK project right after triggers
were first implemented:
.LP
BitKeeper/triggers/post\-incoming:
.DS
#!/bin/sh

shift
REPO=`bk gethost`:`pwd`
if [ "$BK_INCOMING" = OK \-a \-f BitKeeper/etc/csets ]
then    ( 
	echo ${USER}@"$@"
	echo ""
	bk changes \-r`cat BitKeeper/etc/csets`
	) | mail \-s "Incoming to $REPO" lm@bitmover.com
fi
.DE
BitKeeper/triggers/post\-outgoing:
.DS
#!/bin/sh

shift
REPO=`bk gethost`:`pwd`
TO=lm@bitmover.com
if [ \-f BitKeeper/etc/pushed \-a "$BK_OUTGOING" = OK ]
then	( 
	echo ${USER}@"$@"
	echo ""
	bk changes \- < BitKeeper/etc/pushed
	) | mail \-s "Outgoing from $REPO" $TO
else
	echo ${USER}@"$@"| mail \-s "Outgoing from $REPO = $BK_OUTGOING" $TO
fi
.DE
Example output from a pull:
.DS
From: Larry McVoy <lm@bitmover.com>                                             
Date: Sun, 28 May 2000 16:48:57 -0700
To: lm@bitmover.com
Subject: Incoming to work.bitmover.com:/tmp/TRIGGERS                                

lm@work.bitmover.com:/tmp/TRIGGERS pull work.bitmover.com:/home/bk/exit

ChangeSet@1.735, 2000-05-28 01:41:31-07:00, orc@india.pell.portland.or.us
  More work on triggers.  Now triggers are fired from within the
  cmdlog_start() and cmdlog_end() functions, and they now support
  path\-specific triggers as well as triggers that everyone else
  will use.
	 
ChangeSet@1.734, 2000-05-27 23:49:25-07:00, orc@india.pell.portland.or.us
  bk-aout.diff

ChangeSet@1.733, 2000-05-27 14:24:48-07:00, lm@work.bitmover.com
  Merge work.bitmover.com:/home/bk/stable
	into work.bitmover.com:/home/bk/exit

ChangeSet@1.731.1.1, 2000-05-27 14:16:42-07:00, lm@work.bitmover.com
  Forgot to wait for child process in changes.c.
.DE
.\" help://Repository/notification
.\" help://Repository/notify
.SH AVAILABILITY
.\" XXX not sure how to word this one. - amy
Pull and push triggers available
with \*(BK Professional only.
.SH CATEGORY
.B Repository
