.so ../bk-macros
.TH "bk templates" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk templates \- predefined templates for comments
.SH SYNOPSIS
.B BitKeeper/templates/commit
.SH DESCRIPTION
.LP
Templates are files which are used as the default checkin comments.
Currently only commit templates are implemented.
.LP
If the template exists, then the default comments for a commit are the
contents of the template followed by the per file checkin comments.
In citool, only the template is included.
.SH EXAMPLE
.DS
Bugid:
Requester:
Problem this solves:
.DE
.SH "SEE ALSO"
.SA commit
.SA citool
.\" help://template
.SH CATEGORY
.B Repository
