.so ../bk-macros
.TH "bk unpull" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk unpull \- remove changesets added by bk pull
.SH SYNOPSIS
.B bk unpull 
.[B] \-fqSs
.SH DESCRIPTION
.B bk unpull
will remove changesets added by the most recent
.B bk pull
command.
If a local changeset has been committed,
.B bk unpull
can not be executed
until that changeset is removed by
.BR "bk undo" .
.SH NOTE
.B bk unpull
will discard the merge changeset, if any; that is not considered part of
the local work in this context.
If the merge was complicated it is advisable to save a patch.
.SH OPTIONS
.TP "\\fB\\-\\-standalone \\fP"
.tp
.B \-f
Force unpull.
.tp
.B \-q
Quiet mode.
.if \n[NESTED] \{\
.tp
.B \-S
.tp
.B \-\-standalone
In a nested collection this makes unpull operate only on the
current component.  This is useful to revert a
.B port
command.
\}
.tp
.B \-s
Do not save a backup patch in
.BR BitKeeper/tmp/unpull.patch .
.SH "SEE ALSO"
.SA pull
.SA undo
.SH CATEGORY
.B Common
.br
.B Repository
