.so bk-macros
.TH "bk undo" 1 20%E% "\*(BC" "\*(UM"
.\"    ====================== BitKeeper undo ======================
.SH NAME
bk undo \- Undo a changeset or set of changesets
.SH SYNOPSIS
.\" XXX - lm, what to do with these [] around -a and -r arguments?
.Bc bk undo [\-fqs] \-a[
.ARGc rev 
.Bc ] | \-r[
.ARGc revs
.B ]
.SH DESCRIPTION
.LP
The undo command can be used to remove any changeset or set of
changesets.   There are options to select specific changesets or all
changesets after some point (which is what
.B bk clone \-r
uses.)
.LP
To undo a bk pull use bk unpull.
.SH WARNING
.LP
You can not undo an undo.  If the data was only present in your
repository, when you undo it, it is gone for good.
.SH OPTIONS
.if t .TP 
.if n .TP 1i
.OPTreq \-a rev
Remove all changesets which occurred after 
.ARG rev .
If 
.ARG rev
is what you want to have be top of trunk,
use this option.
.tp
.B \-f
Force the undo to complete if it can.  Normally, undo will
prompt with a list of deltas which will be removed.
.tp
.B \-q
Run quietly; do not list files.
.tp
.B \-s
Do not save undone changes as a patch.
.tp
.OPTreq \-r revs
Remove the list of changesets specified by 
.ARG revs .
.ARG revs
must be of the form r1,r2,r3, etc.
.SH "SEE ALSO"
.LP
.SA makepatch 1
.SA stripdel 1
.SA takepatch 1
.SA unpull 1
.SH CATEGORY
.B Repository
