.so bk-macros
.TH "bk unpark" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk unpark \- resume work
.SH SYNOPSIS
.Bc bk unpark [
.ARG parkfile-n ]
.SH DESCRIPTION
To return a repository to its pre-parked state use bk unpark.
To list parkfiles and comments, use bk park -l.
.SH "SEE ALSO"
.SA park 1
.SH CATEGORY
.B Repository
