.so bk-macros
.TH "bk url" 1 20%E% "\*(BC" "\*(UM"
.SH NAME
bk url \- methods of accessing \*(BK repositories
.SH DESCRIPTION
\*(BK supports many ways to access a repository.  The selection of the
access method is determined by how the repository is referenced.  Each
reference form is described below with an explanation of how the repository
is accessed following each form.
.SH ACCESS METHODS
.SS LOCAL
.in +4
.de head
.	br
.	ne 4
.	ti -4
..
.head
.ARG pathname
.br
Access is all local, through the local file system.
.head
.ARGc host :
.ARG pathname
.br
Normally a remote repository unless 
.ARG host 
is what
.B bk host
returns or is
.BR localhost .
In either of those cases, this form is the same as the above form.
.SS RSH
.in +4
.head
\fBrsh\fR://\c
.ARGc host :
.ARG pathname
.br
.head
\fBrsh\fR://\c
.ARGc user @
.ARGc host :
.ARG pathname
.br
Uses
.B rsh
to access
.ARG host ,
and starts a temporary
.BR bkd .
.SS SSH
.in +4
.head
.ARGc host :
.ARG pathname
.br
.head
.ARGc user @
.ARGc host :
.ARG pathname
.br
Uses 
.B ssh 
(by default)
to access 
.ARG host ,
and starts a temporary
.BR bkd .
If 
.B $BK_RSH 
is set, then use that to talk to the host (allows proxying).
If no 
.B ssh
is found then falls back to
.BR rsh.
.head
\fBssh\fR://\c
.ARGc host :
.ARG pathname
.br
.head
\fBssh\fR://\c
.ARGc user @
.ARGc host :
.ARG pathname
.br
Uses
.B ssh
to access
.ARG host ,
and starts a temporary
.BR bkd .
.head
\fBbk\fR://\c
.ARGc user @
.ARG host 
.br
Connects to
.ARG host
using 
.BR ssh ,
assumes that 
.B bkd
is the login shell.
The home directory of 
.ARG user
must be the root of the repository.
.head
\fBbk\fR://\c
.ARGc user @
.ARGc host :
.ARG pathname
.br
Connects to
.ARG host
using 
.BR ssh ,
assumes that 
.B bkd
is the login shell.
Changes directories to the specified pathname, which may be relative to the
home directory or absolute.
.SS BKD
.in +4
.head
\fBbk\fR://\c
.ARG host
.br
Connects to an existing 
.B bkd
on the default 
.B bkd
port.
The 
.B bkd
must be at the root of the repository.
.head
\fBbk\fR://\c
.ARGc host /
.ARGc rel /
.ARG path
OR\ \fBbk\fR//\c
.ARGc host /
.ARGc rel /
.ARG path
.br
Connects to an existing 
.B bkd
on the default bkd port,
changes to 
.ARGc rel /
.ARG path ,
then runs command.  Where
.ARGc rel /
.ARG path
is the path relative to the root of the repository.
.head
\fBbk\fR://\c
.ARGc host //
.ARGc full /
.ARG path
OR\ \fBbk\fR//\c
.ARGc host //
.ARGc full /
.ARG path
.br
Connects to an existing 
.B bkd
on the default bkd port,
changes to 
.ARGc full /
.ARG path ,
then runs command.  Where
.ARGc full /
.ARG path
is the absolute path.
.head
\fBbk\fR://\c
.ARGc host :
.ARG port
.br
Connects to an existing 
.B bkd
on the specified port.
.B bkd
must be at the root of the repository.
.head
\fBbk\fR://\c
.ARGc host :
.ARGc port /
.ARG pathname
.br
Connects to an existing 
.B bkd
on the specified port,
changes to 
.ARG pathname ,
then runs command.
.SS HTTPD
.in +4
.head
\fBhttp\fR://\c
.ARGc host :
.ARGc port /
.ARGc relative /
.ARG path
.br
Connects to the specified port via the hypertext transfer protocol, changes
to pathname, then runs the command.  Where
.ARGc relative /
.ARG path
is the relative path from the root of the repository.
.head
\fBhttp\fR://\c
.ARGc host :
.ARGc port //
.ARGc full /
.ARG path
.br
Connects to the specified port via the hypertext transfer protocol, changes
to pathname, then runs the command.  Where
.ARGc full /
.ARG path
is the absolute path.
.head
\fBhttp\fR://\c
.ARGc host :
.ARGc port 
.br
Same as above, except that it assumes that the pwd of the bkd is the root
of the source repository.
.SH PROXIES
.LP
\*(BK supports http proxy via environment variables on Unix systems and
via the registry on win32 systems.
.LP
The following are the Unix environment variable options available for use.  
.LP
.RS .4i
.Bc HTTP_PROXY_HOST=
.ARG host_name
.br
.Bc HTTP_PROXY_PORT=
.ARG port_number
.LP
.Bc http_proxy= 
.Bc http://
.ARGc host :
.ARG port
.LP
.Bc SOCKS_HOST=
.ARG host_name
.br
.Bc SOCKS_PORT=
.ARG port_number
.LP
.Bc SOCKS_SERVER=
.ARGc host :
.ARG port
.RE
.LP
Note: if HTTP_PROXY_HOST is set, HTTP_PROXY_PORT must also be set.  Likewise
for SOCKS_HOST and SOCKS_PORT.
If you are not sure if you should set environment variables, please consult
your system administrator.
.\" help://remote
.\" help://naming
.SH CATEGORY
.B Repository
.br
.B Overview
