.so ../bk-macros
.TH "bk unrm" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME 
bk unrm \- resurrect a removed \*(BK file
.SH SYNOPSIS
.B bk unrm
.ARG file
.SH DESCRIPTION
.LP
Use
.B bk unrm
to resurrect a file that has been deleted using
.BR "bk rm" .
Please note that
.B bk unrm
cannot resurrect files that have been removed 
from the source tree using
.BR "bk gone" .
.LP
If you know the path to the original file, for example
.BR src/Makefile ,
then to resurrect:
.DS
cd ~/projects/myproject/src
bk unrm Makefile
.DE
If you do not know the directory run unrm from the root of the repository:
.DS
cd ~/projects/myproject
bk unrm Makefile
.DE
There will be an interactive interface for choosing whether or not to 
resurrect the file.  Type
.Q y
to resurrect the file,
.Q n
to do nothing or go to the next option, or
.Q q
to quit.  If there are more than one files
with the same name, choose
.Q y
if the pathname shown is the one you want, or choose
.Q n
until the correct file is shown.
.SH SEE ALSO
.SA gone
.SA rm
.SA rmdir
.SH CATEGORY
.B Common
.br
.B File
