.so ../bk-macros
.TH "bk unwrap" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.\"    =============== Unwrapping BitKeeper patches ===============
.SH NAME
bk unwrap \- unwrap patches
.SH SYNOPSIS
.B bk unwrap \< 
.ARG patch 
.B \>
.ARG patch.unwrapped
.SH DESCRIPTION
.LP
Normally you do not use this command as it is invoked automatically
as part of the
.B bk receive
command.
However, you may want to use this command to peek inside a wrapped
patch.
.SH SEE ALSO
.SA receive
.SA send
.SA wrap
.SH CATEGORY
.B File
