.so ../bk-macros
.TH "bk xflags" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk xflags \- check or fix BitKeeper flags
.SH SYNOPSIS
.B bk
.B xflags
.[B] \-ns
.FILES
.SH DESCRIPTION
.LP
.B bk xflags
is an administrative command used to check and/or fix \*[BK] 
flags.  These flags control things such as what sort of keywords are
expanded.
.LP
This command should not be typically needed, it exists to fix older
repositories which did not properly maintain these flags.  If
.B bk check 
yields output like
.DS
src/utils/Makefile@@1.12 should have EXPAND1 flag
src/utils/README@@1.3 should have SCCS flag
src/DOCS: missing required flag[s]: BITKEEPER
.DE
.B bk xflags
needs to be run.
.LP
With no options,
.B bk xflags
will fix the flags in all of the specified files.  To fix all files, run
.DS
bk -A xflags
.DE
.SH OPTIONS
.TP
.B \-n
Do not change any files, just list any problems found.
.tp
.B \-s
Do not change any files, do not list any status, just exit 0 if no
problems were found, exit 1 if problems were found.
.SH SEE ALSO
.SA admin
.SA check
.SH CATEGORY
.B File
