.so ../bk-macros
.TH "bk zone" "\*[BKVER]" %E% "\*(BC" "\*(UM"
.SH NAME
bk zone \- print \*(BK's view of the timezone
.SH SYNOPSIS
.B bk zone
.SH DESCRIPTION
Prints the timezone as an offset from GMT, i.e., PST is -08:00,
PDT is -07:00.
.SH EXIT STATUS
.LP
.B bk zone
returns exit status 0.
.SH CATEGORY
.B Utility
