#include "bkd.h"

/* Keep this alphabetical please */
struct cmd cmds[] = {
  { "?", "?", "print this help", cmd_help },
  { "abort", "abort_1.3", "abort resolve", cmd_abort },
  { "cd", "cd_1.3", "change to a new repository root", cmd_cd },
  { "check", "check_1.3", "check repository", cmd_check },
  { "clone", "clone_1.2", "clone the current repository", cmd_clone },
  { "help", "help_1.3", "print this help", cmd_help },
  { "httpget", "httpget_1.3", "http get command", cmd_httpget },
  { "get", "get_1.3", "http get command", cmd_httpget },
  { "pull", "pull_1.2",
    "pull remote changes from current repository into client repository",
    cmd_pull },
  { "push", "push_1.2",
    "push and apply local changes into remote repository", cmd_push },
  { "pwd", "pwd_1.3", "show current working directory", cmd_pwd },
  { "quit", "quit_1.3", "disconnect and end conversation", cmd_eof },
  { "rootkey", "rootkey_1.3", "show the ChangeSet root key", cmd_rootkey },
  { "status", "status_1.3", "Show status for repository", cmd_status },
  { "version", "version_1.3", "Show bkd version", cmd_version },
  { "putenv", "putenv.1.3", "set up environment variable", cmd_putenv },
  { "push_part1", "push_1.3_part1", 
	"push and apply local changes into remote repository", cmd_push_part1 },
  { "push_part2", "push_1.3_part2", 
	"push and apply local changes into remote repository", cmd_push_part2 },
  { "pull_part1", "pull_1.3_part1",
    "pull remote changes from current repository into client repository",
    cmd_pull_part1 },
  { "pull_part2", "pull_1.3_part2",
    "pull remote changes from current repository into client repository",
    cmd_pull_part2 },
  { "rclone_part1", "rclone_1.3_part1", 
    "clone local repository to remote repository",
    cmd_rclone_part1 },
  { "rclone_part2", "rclone_1.3_part2", 
    "clone local repository to remote repository",
    cmd_rclone_part2 },
  { 0, 0, 0 }
};
