#!/bin/sh
# Copyright 2005,2016 BitMover, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test "$MSYSBUILDENV" || {
	echo running in wrong environment, respawning...
	rm -f conf-*.mk
	bk get -S ./update_buildenv
	BK_USEMSYS=1 bk sh ./update_buildenv
	export HOME=`bk pwd`
	test -d R:/build/buildenv/bin &&
	    exec R:/build/buildenv/bin/sh --login -i
	exec C:/build/buildenv/bin/sh --login -i
}
